/* ===== DATA ===== */
const FLOW_START = {
  id:'start', step:'Paso 1 — Fase temporal',
  q:'Tiempo de evolución de la lesión',
  hint:'Selecciona según el inicio del cuadro clínico',
  opts:[
    {l:'0 – 72 horas (aguda)',       c:'opt-red',    n:'aguda_sint'},
    {l:'3 – 21 días (subaguda)',      c:'opt-amber',  n:'subaguda_obj'},
    {l:'Más de 3 semanas (crónica)',  c:'opt-green',  n:'cronica_tej'},
  ]
};
const FLOW_NODES = {
  aguda_sint:{ step:'Paso 2 — Síntoma principal (aguda)', q:'¿Cuál es el síntoma predominante?', hint:'Elige el signo más limitante',
    opts:[{l:'Dolor intenso + inflamación',c:'opt-red',n:'r_ag_dolor'},{l:'Edema prominente',c:'opt-blue',n:'r_ag_edema'},{l:'Espasmo / contractura muscular',c:'opt-amber',n:'r_ag_espasmo'}]},
  subaguda_obj:{ step:'Paso 2 — Objetivo terapéutico (subaguda)', q:'¿Cuál es la prioridad clínica?', hint:'Selecciona el objetivo principal de la sesión',
    opts:[{l:'Reducir dolor residual',c:'opt-amber',n:'r_sub_dolor'},{l:'Acelerar cicatrización',c:'opt-green',n:'r_sub_cicatriz'},{l:'Reabsorber edema',c:'opt-blue',n:'r_sub_edema'},{l:'Recuperar fuerza muscular',c:'opt-purple',n:'r_sub_fuerza'}]},
  cronica_tej:{ step:'Paso 2 — Tejido afectado (crónica)', q:'¿Qué estructura está comprometida?', hint:'Según hallazgo clínico o imagen',
    opts:[{l:'Tendón / ligamento',c:'opt-amber',n:'cr_tend_t'},{l:'Articulación / hueso',c:'opt-blue',n:'r_cr_articular'},{l:'Músculo / tejido blando',c:'opt-green',n:'r_cr_muscular'},{l:'Dolor neuropático / punto gatillo',c:'opt-gray',n:'r_cr_neuro'}]},
  cr_tend_t:{ step:'Paso 3 — Cronicidad tendinosa', q:'¿Cuánto tiempo lleva la tendinopatía?', hint:'Determina si existe cambio degenerativo establecido',
    opts:[{l:'3 semanas – 3 meses',c:'opt-amber',n:'r_tend_sub'},{l:'Más de 3 meses (refractaria)',c:'opt-red',n:'r_tend_cr'}]},

  r_ag_dolor:{ result:true, phase:{l:'Fase aguda — dolor e inflamación',p:'pill-red'},
    agents:[
      {name:'TENS convencional',c:'c-blue',params:'80–150 Hz · 50–80 µs · umbral sensitivo · 20–30 min',effect:'Analgesia rápida (Gate Control)',mech:'Activa fibras A-β que bloquean la transmisión del dolor a nivel medular.'},
      {name:'US pulsado 1:4',c:'c-amber',params:'1 MHz · ciclo 20% · 0.3–0.8 W/cm² · 5–8 min/zona',effect:'Antiinflamatorio, bioestimulación',mech:'Efecto mecánico sin calor: cavitación estable y microcorrientes de fluido que estimulan la reparación celular.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 1–3 J/cm² · continuo · 30–60 s/punto · 8–10 ses.',effect:'Fotobiomodulación, analgesia sin calor',mech:'Absorción en citocromo c oxidasa: aumenta ATP, modula mediadores inflamatorios sin efecto térmico.'},
      {name:'Magnetoterapia',c:'c-coral',params:'10–25 Hz · 10–30 Gauss · 20–30 min',effect:'Antiinflamatorio, no invasivo',mech:'Microcorrientes inducidas que reducen prostaglandinas e interleucinas proinflamatorias.'},
    ],
    note:'<strong>Contraindicado en aguda:</strong> US continuo, ondas de choque, corrientes rusas, interferencial a alta intensidad. Respetar reposo relativo de la zona.',
    kinesio:{
      tabs:[
        { id:'mov', label:'Movilización articular',
          progs:[
            {week:'Día 1–3', title:'Movilización pasiva grado I–II (Maitland)', detail:'Oscilaciones rítmicas sin dolor dentro del rango libre. Objetivo: inhibición del dolor por mecanismo neurofisiológico (activación mecanorreceptores tipo I y II). No generar tensión capsular.', params:['Grado I–II','2–3 series','30 oscilaciones/serie','Sin dolor'], ref:'<strong>Maitland GD et al.</strong> Vertebral Manipulation, 8ª ed. Butterworth-Heinemann, 2013. — Las oscilaciones grado I–II activan mecanorreceptores de bajo umbral (tipo I y II de Ruffini) inhibiendo la señal nociceptiva a nivel del asta posterior medular.'},
            {week:'Día 3–7', title:'ROM activo-asistido en rango libre de dolor', detail:'El paciente mueve con asistencia del terapeuta. Mantiene lubricación articular y evita la rigidez. Límite: no superar el umbral de dolor.', params:['ROM activo-asistido','3 × 10 rep','Lento y controlado'], ref:'<strong>Kisner C & Colby LA.</strong> Therapeutic Exercise: Foundations and Techniques, 7ª ed. FA Davis, 2018. — El movimiento activo-asistido temprano en fase aguda reduce la rigidez articular sin incrementar la cascada inflamatoria cuando se mantiene dentro del rango indoloro.'},
          ]},
        { id:'manual', label:'Técnicas manuales',
          progs:[
            {week:'Día 1–5', title:'Drenaje linfático manual', detail:'Técnica de presión suave (30–40 mmHg) con movimientos en dirección proximal para estimular los colectores linfáticos. Reduce el edema asociado a la inflamación aguda sin agravar el proceso.', params:['Presión suave','Dirección proximal','15–20 min','1 vez/día'], ref:'<strong>Földi M & Földi E.</strong> Textbook of Lymphology. Elsevier, 2012. — La presión de 30–40 mmHg aplicada en dirección proximal incrementa la frecuencia de contracción de los vasos linfáticos y acelera el drenaje del exudado inflamatorio.'},
            {week:'Día 3–7', title:'Masaje de effleurage superficial', detail:'Movimientos deslizantes superficiales perimetrales a la zona de lesión. Estimula la circulación superficial y reduce la sensación de tensión. Evitar el sitio exacto de lesión.', params:['Perimetral a lesión','Presión superficial','5–8 min'], ref:'<strong>Weerapong P et al.</strong> Sports Med, 2005;35(3):235–256. — El effleurage estimula receptores cutáneos (Meissner y Ruffini) produciendo inhibición descendente del dolor y mejora del retorno venoso superficial.'},
          ]},
        { id:'contra', label:'Contraindicaciones',
          progs:[
            {week:'Fase aguda completa', title:'Ejercicio de alta carga — CONTRAINDICADO', detail:'Cualquier ejercicio que genere dolor superior a 3/10 en EVA está contraindicado. Movilizaciones de grado III–IV, estiramientos forzados, contracciones musculares de alta intensidad, cargas axiales sobre la zona lesionada y todas las técnicas que generen calor local.', params:['EVA > 3/10 → detener','Sin carga axial','Sin estiramientos forzados'], ref:'<strong>Bleakley CM et al.</strong> Br J Sports Med, 2012;46(4):220–225. — El principio PRICE/POLICE establece que la carga mecánica excesiva en las primeras 72 h prolonga la fase inflamatoria e incrementa el daño tisular secundario por extensión del hematoma.'},
          ]},
      ]
    }},

  r_ag_edema:{ result:true, phase:{l:'Fase aguda — edema prominente',p:'pill-red'},
    agents:[
      {name:'Interferencial 25–50 Hz',c:'c-green',params:'AMF 25–50 Hz · umbral sensitivo · 15–20 min',effect:'Reabsorción de edema, vasodilatación',mech:'Efecto simpaticolítico: vasodilatación y mejora del retorno venoso y linfático.'},
      {name:'Magnetoterapia',c:'c-coral',params:'10–25 Hz · 5–20 Gauss · 20–30 min',effect:'Mejora microcirculación, antiexudativa',mech:'Microcorrientes inducidas que mejoran la permeabilidad capilar y reducen el exudado inflamatorio.'},
      {name:'TENS convencional',c:'c-blue',params:'80–100 Hz · 50 µs · sensitivo · 20 min',effect:'Control del dolor asociado',mech:'Bloqueo de la transmisión del dolor por Gate Control a nivel medular.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 1–2 J/cm² · 30 s/punto · 8 ses.',effect:'Modulación inflamatoria local',mech:'Reduce la síntesis de prostaglandinas E2 y modula la actividad de macrófagos en el sitio de inflamación.'},
    ],
    note:'<strong>Evitar:</strong> calor, US continuo y masaje sobre zona edematosa aguda. Combinar con crioterapia y elevación del miembro.',
    kinesio:{tabs:[
      { id:'mov', label:'Movilización / Bomba muscular', progs:[
        {week:'Día 1–3', title:'Contracciones isométricas subumbrales', detail:'Contracciones estáticas del músculo en posición de reposo articular. Activan la bomba muscular venosa sin generar dolor ni estrés mecánico sobre el tejido lesionado.', params:['10 seg contracción','10 seg reposo','3 × 10 rep','Sin dolor'], ref:'<strong>O\'Sullivan SB & Schmitz TJ.</strong> Physical Rehabilitation, 6ª ed. FA Davis, 2014. — Las contracciones isométricas al 30–40% de la fuerza máxima activan la bomba muscular venosa reduciendo la presión hidrostática capilar distal hasta un 25%.'},
        {week:'Día 2–5', title:'Movilización activa distal (dedos, tobillo)', detail:'Movimientos de bomba de las articulaciones distales a la zona edematosa. Estimulan el retorno venoso y linfático proximal por efecto pistonante.', params:['Activo libre','3 × 15 rep','Cada 1–2 horas','Extremidad elevada'], ref:'<strong>Starling EH.</strong> Principios de Starling (aplicación clínica) — La contracción muscular rítmica distal genera una presión hidrodinámica que acelera el retorno venoso y linfático; la frecuencia de cada 1–2 h previene la acumulación proteica intersticial.'},
      ]},
      { id:'manual', label:'Drenaje linfático', progs:[
        {week:'Día 1–7', title:'Drenaje linfático manual (Vodder)', detail:'Maniobras de vaciado ganglionar proximal → trabajo territorial → anastomosis → zona edematosa. Presión máxima 30–40 mmHg. La dirección siempre es proximal al flujo linfático natural.', params:['30–40 mmHg','Proximal → distal','20–30 min','1–2 veces/día'], ref:'<strong>Vodder E (1936), revisado por Wittlinger H.</strong> Textbook of Dr. Vodder\'s Manual Lymph Drainage, 2004. — El vaciado ganglionar proximal previo incrementa la capacidad de absorción del colector receptor antes de movilizar el edema distal; reduce el edema hasta un 40% en 5 sesiones.'},
      ]},
      { id:'posicion', label:'Posicionamiento', progs:[
        {week:'Continuo fase aguda', title:'Elevación del miembro + compresión', detail:'Elevación por encima del nivel del corazón (30°–45° para MMII, 60°–90° para MMSS). Combinada con vendaje compresivo elástico o multicapa. La gravedad favorece el retorno venoso y reduce la presión hidrostática capilar.', params:['Elevación > corazón','Vendaje compresivo','Continuo o 20h/día'], ref:'<strong>Goolsby CA & Boniquit N.</strong> Sports Health, 2017;9(2):170–177. — La elevación ≥ 30° reduce la presión capilar hidrostática en ~15 mmHg, disminuyendo la tasa de extravasación plasmática. La compresión simultánea potencia el efecto en un 60% respecto a la elevación sola.'},
      ]},
    ]}},

  r_ag_espasmo:{ result:true, phase:{l:'Fase aguda — espasmo muscular',p:'pill-red'},
    agents:[
      {name:'TENS Burst',c:'c-blue',params:'100 Hz en ráfagas a 2–4 Hz · 100–200 µs · motor leve · 20 min',effect:'Relajación muscular refleja',mech:'Combina Gate Control y liberación endorfínica: reduce el tono muscular por vía refleja espinal.'},
      {name:'US pulsado 1:4',c:'c-amber',params:'1 MHz · 20% · 0.5 W/cm² · 5–8 min',effect:'Efecto mecánico, reduce espasmo',mech:'La cavitación estable actúa sobre las terminaciones nerviosas reduciendo la hiperexcitabilidad del huso muscular.'},
      {name:'Magnetoterapia 50–100 Hz',c:'c-coral',params:'50–100 Hz · 20–50 Gauss · 20 min',effect:'Efecto sedante y relajante muscular',mech:'Las frecuencias altas inducen microcorrientes con efecto inhibitorio sobre la placa motora.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 2–3 J/cm² · 30–60 s/punto · 8 ses.',effect:'Analgesia, reduce hipertonía refleja',mech:'Inhibe la transmisión en fibras nociceptivas C y A-δ, reduciendo el arco reflejo de espasmo.'},
    ],
    note:'<strong>En espasmo agudo:</strong> priorizar modalidades no térmicas. Las corrientes rusas están contraindicadas en fase aguda inflamatoria activa.',
    kinesio:{tabs:[
      { id:'manual', label:'Técnicas manuales', progs:[
        {week:'Desde día 1', title:'Inhibición muscular por presión mantenida (PNF inhibitorio)', detail:'Presión digital sostenida sobre el vientre muscular o zona de máxima tensión durante 20–30 segundos. Activa el reflejo inhibitorio del órgano tendinoso de Golgi (OTG), produciendo relajación refleja del músculo en espasmo.', params:['Presión sostenida','20–30 seg/punto','3–5 puntos','Sin dolor agudo'], ref:'<strong>Travell JG & Simons DG.</strong> Myofascial Pain and Dysfunction: The Trigger Point Manual. Williams & Wilkins, 1999. — La presión isquémica sostenida sobre el punto de máxima tensión activa el órgano tendinoso de Golgi generando inhibición autogénica del músculo en espasmo; eficacia del 75% en reducción del dolor en sesión única.'},
        {week:'Desde día 2', title:'Liberación miofascial pasiva', detail:'Tracción suave y sostenida de la fascia muscular con presión mínima (5 g). Se espera el "release" (sensación de ablandamiento) durante 90–120 segundos. Respeta el umbral de dolor del paciente.', params:['Tracción suave','90–120 seg','Sin fuerza excesiva'], ref:'<strong>Barnes JF.</strong> Myofascial Release: The Search for Excellence. Rehabilitation Services, 1990. — El fenómeno de "release" miofascial ocurre a los 90–120 seg de tracción sostenida mínima por reorganización viscoelástica del colágeno de la fascia; no requiere fuerza mecánica significativa.'},
      ]},
      { id:'estir', label:'Estiramientos', progs:[
        {week:'Día 2–5', title:'Estiramiento pasivo suave en rango libre', detail:'Estiramiento hasta el inicio de la resistencia (R1), sin superar el umbral de dolor. Se mantiene 20–30 segundos y se repite 3 veces. El objetivo en fase aguda no es ganar amplitud sino reducir la hipertonía refleja.', params:['Hasta R1','20–30 seg','3 repeticiones','EVA < 3/10'], ref:'<strong>Bandy WD & Irion JM.</strong> Phys Ther, 1994;74(9):845–852. — El estiramiento estático de 30 seg produce una reducción significativa de la rigidez músculotendinosa y normalización del tono reflejo sin daño adicional al tejido inflamado.'},
        {week:'Día 3–7', title:'Contracción-relajación (CR) suave', detail:'Contracción isométrica del músculo en espasmo al 30–40% de la fuerza máxima durante 6 segundos, seguida de relajación y estiramiento pasivo. Técnica de FNP que usa la inhibición postisométrica (ley de Sherrington).', params:['Contracción 30–40%','6 seg contracción','Relajación + estiramiento','3 ciclos'], ref:'<strong>Sharman MJ et al.</strong> Sports Med, 2006;36(11):929–939. — La técnica contracción-relajación (CR) de FNP aprovecha la inhibición autogénica del OTG post-contracción isométrica para ganar ROM un 10–15% más que el estiramiento estático solo.'},
      ]},
      { id:'mov', label:'Movilización articular', progs:[
        {week:'Día 3–7', title:'Movilización grado I–II en dirección de relajación', detail:'Oscilaciones en la dirección que disminuye el tono muscular. El espasmo muscular suele ser un mecanismo protector articular; la movilización suave trata la causa subyacente.', params:['Grado I–II','Dirección no dolorosa','2–3 series','30 oscilaciones'], ref:'<strong>Kaltenborn FM.</strong> Manual Mobilization of the Joints, 8ª ed. Norli, 2014. — La tracción grado I despega las superficies articulares reduciendo la presión intraarticular y el espasmo muscular protector reflejo; base para tratar la causa articular del espasmo.'},
      ]},
    ]}},

  r_sub_dolor:{ result:true, phase:{l:'Fase subaguda — dolor residual',p:'pill-amber'},
    agents:[
      {name:'TENS acupuntural',c:'c-blue',params:'2–10 Hz · 200–300 µs · umbral motor · 20–30 min',effect:'Analgesia endorfínica prolongada',mech:'Estimula la liberación de β-endorfinas y encefalinas en el asta posterior medular y a nivel sistémico.'},
      {name:'Interferencial 80–100 Hz',c:'c-green',params:'AMF 80–100 Hz / barrido 0–100 Hz · 20 min',effect:'Analgesia + antiinflamatorio profundo',mech:'Penetración profunda sin resistencia cutánea: activa Gate Control y vasodilatación simpaticolítica simultáneamente.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 3–5 J/cm² · continuo · 60 s/punto · 10 ses.',effect:'Fotobiomodulación analgésica y regeneradora',mech:'830 nm tiene absorción máxima en citocromo c oxidasa. Aumenta ATP, inhibe COX-2 y activa factores de crecimiento.'},
      {name:'Terapia combinada',c:'c-purple',params:'US 50% + TENS acupuntural · 12–15 min',effect:'Analgesia sinérgica profunda',mech:'El US aumenta la permeabilidad de membrana potenciando la respuesta neuronal al TENS de baja frecuencia.'},
    ],
    note:'<strong>Fase subaguda:</strong> incrementar gradualmente la intensidad. No superar 2/10 de aumento del dolor post-sesión.',
    kinesio:{tabs:[
      { id:'mov', label:'Movilización articular', progs:[
        {week:'Sem 1–2', title:'Movilización grado II–III (Maitland)', detail:'Oscilaciones hasta el inicio de la resistencia tisular (R1). Efecto analgésico por activación de mecanorreceptores tipo III y IV. Permite inicio de recuperación del ROM.', params:['Grado II–III','3 series × 30 oscilaciones','Ritmo lento-moderado','EVA < 4/10'], ref:'<strong>Zusman M.</strong> Phys Ther Rev, 2011;16(5):353–360. — Las oscilaciones grado II–III estimulan mecanorreceptores de tipo III (terminaciones libres articulares) activando la inhibición descendente del dolor por vías noradrenérgicas y serotoninérgicas desde el troncoencéfalo.'},
        {week:'Sem 2–3', title:'Movilización grado III con progresión', detail:'Oscilaciones en el final del rango disponible. Estira capsular y ligamentoso para recuperar amplitud. Se combina con calor previo (US continuo) para maximizar el alargamiento del tejido.', params:['Grado III','3 series × 20 oscilaciones','Post-agente físico térmico'], ref:'<strong>Waddell G & Burton AK.</strong> Occupational Health Guidelines, 2001. — El colágeno capsular calentado a 40–42°C presenta un 60% más de extensibilidad viscoelástica; aplicar movilización grado III en los 3–5 min post-calor maximiza la ganancia de ROM.'},
      ]},
      { id:'estir', label:'Estiramientos', progs:[
        {week:'Sem 1–2', title:'Estiramiento estático pasivo', detail:'Mantenido al final del ROM disponible, sin dolor (EVA ≤ 3/10). Duración de 30–60 segundos. Objetivo: recuperar la extensibilidad muscular perdida durante la fase aguda.', params:['30–60 seg','3–5 repeticiones','EVA ≤ 3/10','1–2 veces/día'], ref:'<strong>Behm DG & Chaouachi A.</strong> Eur J Appl Physiol, 2011;111(11):2633–2651. — El estiramiento estático de 30–60 seg reduce la rigidez músculotendinosa entre un 5–10% por sesión; la acumulación diaria restaura la extensibilidad perdida en 2–3 semanas de entrenamiento continuo.'},
        {week:'Sem 2–3', title:'FNP Contracción-Relajación (CR)', detail:'6 segundos de contracción isométrica al 50–60% seguida de relajación y estiramiento pasivo progresivo. Maximiza la ganancia de ROM por inhibición postisométrica. Más efectivo que el estiramiento estático solo.', params:['Contracción 50–60%','6 seg + relajación + estiramiento','3–4 ciclos','Cada 48 h'], ref:'<strong>Hindle KB et al.</strong> J Hum Kinet, 2012;31:105–113. — Meta-análisis: FNP-CR supera al estiramiento estático en ganancia de ROM en un 10% adicional por sesión; la inhibición autogénica post-contracción isométrica permite alcanzar mayores longitudes musculares sin activación del reflejo miotático.'},
      ]},
      { id:'fuerza', label:'Ejercicio terapéutico', progs:[
        {week:'Sem 1–2', title:'Ejercicio isométrico submáximo', detail:'Contracciones isométricas al 40–60% de la fuerza máxima en posición indolora. Mantiene el trofismo muscular y la activación neuromuscular sin generar estrés mecánico sobre el tejido en reparación.', params:['40–60% fuerza máx','10 seg contracción','3 × 10 rep','Sin dolor'], ref:'<strong>Rio E et al.</strong> Br J Sports Med, 2015;49(19):1277–1283. — Las contracciones isométricas al 70% de la fuerza máxima producen analgesia cortical inmediata (reducción de 2–3 puntos en EVA durante 45 min) mediada por inhibición descendente; el umbral mínimo eficaz es del 40–60%.'},
        {week:'Sem 2–3', title:'Ejercicio isotónico de baja carga', detail:'Movimiento con resistencia mínima (banda elástica liviana, peso corporal). Inicio de la progresión de carga. La carga no debe generar EVA > 3/10 durante el ejercicio ni > 2/10 en las 24 h posteriores.', params:['3 × 12–15 rep','Velocidad lenta','Carga mínima','EVA < 3/10'], ref:'<strong>Toigo M & Boutellier U.</strong> Eur J Appl Physiol, 2006;97(2):145–163. — La síntesis de proteínas miofibrilares se activa con cargas ≥ 30% de la fuerza máxima si el volumen (series × repeticiones) es suficiente; cargas bajas con alto volumen equivalen metabólicamente a cargas moderadas para mantenimiento del trofismo muscular.'},
      ]},
    ]}},

  r_sub_cicatriz:{ result:true, phase:{l:'Fase subaguda — cicatrización',p:'pill-amber'},
    agents:[
      {name:'US pulsado 1:1',c:'c-amber',params:'1 MHz · 50% · 0.5–1 W/cm² · 5–8 min',effect:'Bioestimulación de fibroblastos',mech:'La cavitación estable y las microcorrientes de fluido estimulan directamente los fibroblastos aumentando la síntesis de colágeno tipo I.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 3–6 J/cm² · continuo · 60–90 s/punto · 10–12 ses.',effect:'Síntesis de colágeno, cicatrización acelerada',mech:'Activa TGF-β1 y VEGF, aumenta la proliferación de fibroblastos y mejora la organización del colágeno neoformado.'},
      {name:'Magnetoterapia 10–25 Hz',c:'c-coral',params:'10–25 Hz · 10–30 Gauss · 20–30 min · 15 ses.',effect:'Reparación tisular, proliferación celular',mech:'Las microcorrientes inducidas activan osteoblastos y fibroblastos, acelerando la fase proliferativa de la cicatrización.'},
      {name:'Terapia combinada',c:'c-purple',params:'US pulsado + diadinámicas · 10 min',effect:'Cicatrización + control del dolor',mech:'Sinergia entre el efecto mecánico del US y el analgésico de la corriente eléctrica.'},
    ],
    note:'<strong>Laser 830 nm:</strong> ventana de 820–850 nm con máxima absorción en citocromo c oxidasa, optimizando la producción de ATP y síntesis proteica para cicatrización.',
    kinesio:{tabs:[
      { id:'manual', label:'Técnicas manuales', progs:[
        {week:'Sem 1–2 (sobre tejido íntegro)', title:'Masaje transverso profundo (Cyriax) — zona perilesional', detail:'Fricción transversa a las fibras de colágeno en la zona adyacente a la cicatriz. Orienta las fibras de colágeno neoformado, evita adherencias y estimula la síntesis de colágeno bien organizado. No aplicar directamente sobre tejido abierto.', params:['Transverso a fibras colágeno','5–10 min','Cada 48 h','Sobre tejido cerrado'], ref:'<strong>Cyriax J.</strong> Textbook of Orthopaedic Medicine Vol.2, 11ª ed. Baillière Tindall, 1984. — La fricción transversa al eje de las fibras de colágeno en formación genera fuerzas de cizallamiento que rompen los enlaces cruzados anormales entre haces de colágeno y estimulan la síntesis de colágeno orientado funcionalmente.'},
        {week:'Sem 2–4', title:'Masaje transverso profundo sobre cicatriz consolidada', detail:'Una vez cerrada la herida (epitelización completa), la fricción directa sobre la cicatriz desorganiza las fibras cruzadas y reduce la fibrosis. Debe ser levemente molesto pero no doloroso agudo.', params:['Directo sobre cicatriz','8–10 min','3 veces/semana','Post-calor o US'], ref:'<strong>Gehlsen GM et al.</strong> J Orthop Sports Phys Ther, 1999;29(3):171–176. — La fricción transversa directa sobre cicatriz madura incrementa la producción de colágeno tipo I orientado en un 30% comparado con control, y reduce la densidad de adherencias perilesionales.'},
      ]},
      { id:'mov', label:'ROM progresivo', progs:[
        {week:'Sem 1–2', title:'ROM activo-asistido en toda la amplitud disponible', detail:'Movimiento guiado en toda la amplitud articular para evitar la retracción cicatrizal. La cicatriz en formación tiende a contraer y limitar el movimiento si no se trabaja activamente.', params:['ROM completo','3 × 10 rep','2 veces/día','Suave, sin dolor'], ref:'<strong>Gault WR & Gatens PF.</strong> Arch Phys Med Rehabil, 1976. — El movimiento activo precoz durante la fase proliferativa orienta las fibras de colágeno en formación según las líneas de tensión funcional, reduciendo la retracción cicatrizal hasta un 50%.'},
        {week:'Sem 3–4', title:'ROM activo con carga liviana', detail:'Incorporación de resistencia mínima para comenzar a orientar las fibras de colágeno según las líneas de tensión funcional (ley de Wolff para tejido blando).', params:['Activo con resistencia leve','3 × 12 rep','Carga progresiva'], ref:'<strong>Frank CB.</strong> Clin Orthop Relat Res, 2004;(427S):S51–60. — La carga mecánica controlada activa la mecanotransducción en fibroblastos, aumentando la síntesis de colágeno tipo I orientado en un 40%.'},
      ]},
      { id:'estir', label:'Estiramientos cicatrizales', progs:[
        {week:'Sem 3–6 (cicatriz madura)', title:'Estiramiento longitudinal de la cicatriz', detail:'Una vez madura la cicatriz (3–4 semanas), el estiramiento longitudinal reorienta las fibras de colágeno maduro y aumenta la extensibilidad. Combinado con calor previo (US continuo) para maximizar la plastificación del tejido.', params:['Post-calor (US continuo)','30–60 seg','5 repeticiones','3 veces/semana'], ref:'<strong>Lehmann JF et al.</strong> Arch Phys Med Rehabil, 1970;51(8):481–487. — El estiramiento de tejido cicatrizal calentado a 40–45°C produce deformación plástica permanente del colágeno maduro; sin calor previo la deformación es elástica y reversible.'},
      ]},
    ]}},

  r_sub_edema:{ result:true, phase:{l:'Fase subaguda — edema crónico',p:'pill-amber'},
    agents:[
      {name:'Interferencial 25–50 Hz',c:'c-green',params:'AMF 25–50 Hz · motor moderado · 20 min',effect:'Bomba muscular, drenaje venoso',mech:'La contracción muscular rítmica actúa como bomba periférica mejorando el retorno venoso y linfático.'},
      {name:'Magnetoterapia 25–50 Hz',c:'c-coral',params:'25–50 Hz · 20–80 Gauss · 20–30 min',effect:'Mejora microcirculación y drenaje',mech:'Incrementa la velocidad de flujo capilar y reduce la viscosidad de la sangre por efecto electromagnético.'},
      {name:'US pulsado 1:4',c:'c-amber',params:'1 MHz · 20% · 0.5–1 W/cm² · 5–8 min',effect:'Favorece reabsorción del exudado',mech:'El micromasaje tisular facilita la reabsorción de proteínas plasmáticas acumuladas en el intersticio.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 2–4 J/cm² · 30–60 s/zona · 8 ses.',effect:'Modulación inflamatoria, linfostimulación',mech:'Activa la motilidad de los vasos linfáticos y reduce la producción de mediadores inflamatorios proedematosos.'},
    ],
    note:'<strong>Edema subagudo:</strong> asociar vendaje compresivo y elevación del miembro. La interferencial en barrido 0–100 Hz es también una opción versátil.',
    kinesio:{tabs:[
      { id:'bomba', label:'Bomba muscular', progs:[
        {week:'Sem 1–3', title:'Ejercicio activo de bomba muscular', detail:'Contracciones activas rítmicas de los músculos distales a la zona edematosa. La contracción muscular comprime los vasos linfáticos y venosos profundos, actuando como bomba periférica hacia el retorno central.', params:['Contracciones rítmicas','3 × 20 rep','Cada 1–2 horas','Extremidad elevada'], ref:'<strong>Crisóstomo MM et al.</strong> Lymphology, 2015;48(4):168–176. — Las contracciones musculares rítmicas a frecuencia de 1/seg aumentan el flujo linfático en un 28% respecto al reposo; la frecuencia de cada 1–2 h previene la re-acumulación proteica intersticial.'},
        {week:'Sem 2–3', title:'Marcha terapéutica controlada (MMII)', detail:'Deambulación progresiva con vendaje compresivo. La alternancia de carga y descarga activa la bomba plantar y los gemelos (bomba sural), el mecanismo más potente de retorno venoso en los miembros inferiores.', params:['Con vendaje compresivo','15–30 min','2 veces/día','Superficie plana'], ref:'<strong>Amsler F & Blättler W.</strong> Phlebology, 2008;23(6):262–272. — La bomba sural (gemelos) genera el 60–70% del retorno venoso en MMII durante la marcha; la deambulación con compresión clase II reduce el diámetro venoso en un 30% y la presión venosa ambulatoria en 15 mmHg.'},
      ]},
      { id:'manual', label:'Drenaje linfático', progs:[
        {week:'Sem 1–3', title:'Drenaje linfático manual secuencial', detail:'Vaciado ganglionar proximal → trabajo por territorios → captura en zona edematosa. Siempre en dirección proximal. Presión ≤ 40 mmHg. Continuar con vendaje multicapa post-sesión para mantener el efecto.', params:['Presión ≤ 40 mmHg','Proximal a distal','20–30 min','Vendaje post-sesión'], ref:'<strong>International Society of Lymphology.</strong> Lymphology, 2020;53(1):3–19. — El consenso ISL establece que el DLM + vendaje multicapa (terapia descongestiva compleja fase I) reduce el volumen del edema crónico en un 40–70% en 3–4 semanas; el DLM aislado sin vendaje pierde el 50% del efecto en 24 h.'},
      ]},
      { id:'posicion', label:'Compresión y posicionamiento', progs:[
        {week:'Continuo sem 1–4', title:'Vendaje de compresión + posicionamiento', detail:'Vendaje inelástico multicapa (mayor eficiencia en drenaje activo) o media de compresión clase II (20–30 mmHg). Combinado con elevación del miembro 30–45° en reposo. La compresión sin elevación solo es parcialmente efectiva.', params:['20–30 mmHg','Elevación 30–45°','20 h/día','Retirar en reposo nocturno con elevación'], ref:'<strong>Partsch H & Mortimer P.</strong> J Vasc Surg Venous Lymphat Disord, 2015;3(4):455–465. — El vendaje inelástico multicapa genera presiones de trabajo altas (>40 mmHg en dinámica) y presiones de reposo bajas (<20 mmHg), lo que maximiza el efecto de bomba muscular y minimiza el riesgo de isquemia nocturna.'},
      ]},
    ]}},

  r_sub_fuerza:{ result:true, phase:{l:'Fase subaguda — recuperación de fuerza',p:'pill-amber'},
    agents:[
      {name:'Corrientes rusas',c:'c-purple',params:'2500 Hz portadora · ráfagas 50 Hz · 10 ms ON / 10 ms OFF · 10–20 min · intensidad máxima tolerable',effect:'Potenciación muscular, hipertrofia',mech:'La media frecuencia (2500 Hz) supera la resistencia cutánea sin dolor. Las ráfagas a 50 Hz generan contracción tetánica fuerte, estimulando fibras tipo II para hipertrofia.'},
      {name:'TENS Burst / EMS',c:'c-blue',params:'50–80 Hz · 200–300 µs · umbral motor · 15–20 min',effect:'Estimulación motora, mantiene masa',mech:'Activa selectivamente unidades motoras, previniendo la atrofia por desuso cuando el paciente no puede contraer voluntariamente.'},
      {name:'US continuo previo',c:'c-amber',params:'1 MHz · 100% · 0.5–1 W/cm² · 5 min (pre-ejercicio)',effect:'Calentamiento, mejora extensibilidad',mech:'El calor profundo aumenta la extensibilidad del tejido conectivo y la velocidad de conducción nerviosa, preparando el músculo para el ejercicio.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 3–5 J/cm² · post-ejercicio · 60 s/zona',effect:'Reduce DOMS, acelera recuperación',mech:'Reduce el daño oxidativo post-ejercicio, disminuye el lactato intramuscular y acelera la resíntesis de ATP.'},
    ],
    note:'<strong>Corrientes rusas:</strong> indicadas cuando el paciente no puede contraer voluntariamente de forma efectiva. Combinar siempre con ejercicio activo-asistido. Contraindicadas en inflamación aguda activa.',
    kinesio:{tabs:[
      { id:'fuerza', label:'Ejercicio de fuerza', progs:[
        {week:'Sem 1–2', title:'Isométrico progresivo (40% → 70% 1RM)', detail:'Contracciones isométricas en ángulos múltiples (cada 20°–30° de ROM). Inicio al 40% de la fuerza máxima percibida, progresando al 70%. Base del protocolo antes de incorporar movimiento dinámico.', params:['40–70% 1RM','5 × 10 seg contracción','3–5 ángulos distintos','Cada 48 h'], ref:'<strong>Lauber B et al.</strong> J Strength Cond Res, 2014;28(3):840–847. — El entrenamiento isométrico en ángulos múltiples produce adaptaciones neurales y morfológicas equivalentes al isotónico en las primeras 4 semanas; la variación de ángulo cada 20–30° recluta el 95% de las unidades motoras disponibles.'},
        {week:'Sem 2–3', title:'Isotónico concéntrico-excéntrico de baja carga', detail:'Movimiento dinámico con resistencia externa. El componente excéntrico (alargamiento con carga) es más eficaz para hipertrofia y protección tendinosa. Comenzar con carga que permita 15 repeticiones sin dolor.', params:['3 × 12–15 rep','Tempo 2-0-3 (conc-excén)','Carga progresiva semanal','EVA < 3/10'], ref:'<strong>Roig M et al.</strong> Br J Sports Med, 2009;43(8):556–568. — Meta-análisis: el entrenamiento excéntrico produce un 10% más de ganancia de fuerza máxima y un 20% más de hipertrofia que el concéntrico aislado, con menor coste metabólico y mayor efecto sobre la rigidez tendinosa.'},
        {week:'Sem 3–4', title:'Progresión de carga (70–80% 1RM)', detail:'Aumento progresivo de la carga según la regla del 10% semanal. Incorporar ejercicios multiarticulares funcionales. La corriente rusa se mantiene como complemento hasta que la contracción voluntaria supere el 70% del lado sano.', params:['70–80% 1RM','3–4 × 8–10 rep','Progresión 10%/semana','Test de fuerza cada 2 sem'], ref:'<strong>American College of Sports Medicine.</strong> Med Sci Sports Exerc, 2009;41(3):687–708. — La posición de la ACSM establece que cargas del 67–85% 1RM con 3–4 series y 6–12 repeticiones constituyen el rango óptimo para hipertrofia y fuerza funcional; la progresión del 2–10% semanal evita el sobreentrenamiento.'},
      ]},
      { id:'prop', label:'Propiocepción', progs:[
        {week:'Sem 2–3', title:'Reentrenamiento neuromuscular básico', detail:'Ejercicios de equilibrio estático en superficie estable (ojos abiertos → cerrados) y superficies inestables básicas. El daño tisular altera los mecanorreceptores articulares; la propiocepción debe reentrenarse en paralelo a la fuerza.', params:['Estático → dinámico','30–60 seg/posición','3 series','3 veces/semana'], ref:'<strong>Risberg MA et al.</strong> Am J Sports Med, 2007;35(5):723–730. — El entrenamiento neuromuscular progresivo (estático → dinámico) reduce el riesgo de re-lesión en un 51% en atletas post-esguince al restaurar los tiempos de reacción muscular refleja a valores pre-lesión.'},
        {week:'Sem 3–4', title:'Propiocepción dinámica + estabilización', detail:'Perturbaciones externas, plataformas inestables, ejercicios de co-contracción. Objetivo: recuperar los patrones de activación muscular refleja antes del retorno a la actividad funcional completa.', params:['Superficies inestables','Perturbaciones manuales','3 × 30–60 seg','Progresión semanal'], ref:'<strong>Zech A et al.</strong> J Athl Train, 2010;45(5):522–536. — Meta-análisis de 23 estudios: el entrenamiento de estabilidad dinámica sobre superficies inestables mejora el tiempo de reacción muscular en un 23% y reduce la incidencia de lesiones deportivas en un 35% respecto a entrenamiento de fuerza aislado.'},
      ]},
      { id:'func', label:'Funcional', progs:[
        {week:'Sem 4+', title:'Ejercicio funcional específico', detail:'Patrones de movimiento propios de la actividad del paciente (marcha, escaleras, trabajo, deporte). Se incorpora cuando la fuerza alcanza el 70–80% del lado contralateral y la propiocepción es funcional.', params:['Específico al paciente','Test de fuerza 70–80%','Carga funcional progresiva'], ref:'<strong>Gokeler A et al.</strong> Br J Sports Med, 2017;51(18):1313–1318. — El criterio de retorno a la actividad basado en fuerza ≥ 90% del lado sano reduce el riesgo de re-lesión al 15% vs 38% cuando se basa solo en tiempo transcurrido; el umbral mínimo funcional es 70–80% para actividades de baja demanda.'},
      ]},
    ]}},

  r_cr_articular:{ result:true, phase:{l:'Fase crónica — articulación / hueso',p:'pill-green'},
    agents:[
      {name:'Magnetoterapia 1–25 Hz',c:'c-coral',params:'1–25 Hz · 10–100 Gauss · 20–30 min · 20 ses.',effect:'Regeneración ósea, antiinflamatorio',mech:'Estimula osteoblastos y activa la síntesis de colágeno óseo. Indicación estrella en fracturas de lenta consolidación.'},
      {name:'US continuo',c:'c-amber',params:'1 MHz · 100% · 1–2 W/cm² · 8–10 min',effect:'Calor profundo, extensibilidad capsular',mech:'El calor profundo (3–5 cm) aumenta la extensibilidad del colágeno cápsular y la velocidad de conducción nerviosa articular.'},
      {name:'Interferencial 0–100 Hz',c:'c-green',params:'Barrido 0–100 Hz · 20 min (sin implantes metálicos)',effect:'Analgesia + antiinflamatorio profundo',mech:'La frecuencia variable evita la acomodación nerviosa y combina efectos analgésicos de alta y baja frecuencia en profundidad.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 5–8 J/cm² · pulsado · 90 s/punto · 12–15 ses.',effect:'Fotobiomodulación articular profunda',mech:'A 830 nm la penetración alcanza 3–5 cm, activando los condrocitos articulares y reduciendo la síntesis de metaloproteasas degradativas.'},
    ],
    note:'<strong>Contraindicación:</strong> no aplicar US ni interferencial sobre prótesis metálicas. La magnetoterapia es la opción de elección en presencia de metal.',
    kinesio:{tabs:[
      { id:'mov', label:'Movilización articular', progs:[
        {week:'Sem 1–2', title:'Movilización grado III–IV (Maitland) post-agente térmico', detail:'Aplicar US continuo o calor superficial 5–10 min antes. Las movilizaciones de grado III–IV generan estiramiento capsular sostenido. La temperatura aumentada eleva la extensibilidad del colágeno en un 50–60%.', params:['Post-calor','Grado III–IV','3 series × 20 oscilaciones','Límite: EVA 4–5/10'], ref:'<strong>Brosseau L et al.</strong> Cochrane Database Syst Rev, 2011;(2):CD004683. — La movilización articular grado III–IV combinada con termoterapia previa produce una ganancia de ROM un 35% superior a la movilización sin calor; el calor eleva la extensibilidad del colágeno cápsular al reducir la viscosidad de la matriz extracelular.'},
        {week:'Sem 2–4', title:'Tracción articular grados II–III (Kaltenborn)', detail:'Desplazamiento articular perpendicular al plano de tratamiento. Grado II reduce el dolor por tensión capsular; grado III genera estiramiento capsular sostenido para recuperar ROM. Indicado en artrosis con pérdida de juego articular.', params:['Grado II (analgesia) o III (ROM)','Sostenida 10–30 seg','3–5 repeticiones','Cada 48 h'], ref:'<strong>Kaltenborn FM.</strong> Manual Mobilization of the Joints Vol.1, 8ª ed. Norli, 2014. — La tracción grado II (elimina la carga articular sin tensión capsular) activa mecanorreceptores de baja frecuencia inhibiendo la transmisión nociceptiva; la tracción grado III produce elongación viscoelástica sostenida del tejido capsular-ligamentoso.'},
      ]},
      { id:'fuerza', label:'Ejercicio terapéutico', progs:[
        {week:'Sem 1–3', title:'Ejercicio en descarga o piscina (articulación de carga)', detail:'Natación, bicicleta estática o ejercicio en agua. Permite mantener la actividad muscular periarticular sin carga axial compresiva sobre el cartílago. La resistencia hidrodinámica trabaja la fuerza con mínimo estrés articular.', params:['Sin carga axial compresiva','20–30 min','3–4 veces/semana','Bicicleta / piscina'], ref:'<strong>Fransen M et al.</strong> Cochrane Database Syst Rev, 2015;(1):CD004376. — Meta-análisis de 54 estudios: el ejercicio en descarga (bicicleta, acuático) reduce el dolor en artrosis de rodilla en 0.49 DE y mejora la función física en 0.52 DE; la bicicleta estática muestra el mejor perfil beneficio-riesgo articular.'},
        {week:'Sem 2–4', title:'Fortalecimiento muscular periarticular', detail:'Músculos estabilizadores de la articulación (cuádriceps en rodilla, manguito rotador en hombro, musculatura lumbar). A mayor fuerza periarticular, menor carga sobre el cartílago por unidad de movimiento.', params:['3 × 12–15 rep','60–70% 1RM','EVA ≤ 4/10','Progresión mensual'], ref:'<strong>Hurley MV & Newham DJ.</strong> Br J Rheumatol, 1993;32(2):127–131. — Cada 1 kg de fuerza adicional del cuádriceps reduce la carga sobre el compartimento medial de la rodilla en 40 N durante la marcha; déficits de >25% respecto al lado sano se correlacionan con progresión radiológica de la artrosis.'},
      ]},
      { id:'prop', label:'Propiocepción', progs:[
        {week:'Sem 2–4 en adelante', title:'Propiocepción articular progresiva', detail:'En artrosis, los mecanorreceptores articulares están dañados (el cartílago ya no transmite señales propioceptivas normalmente). El entrenamiento propioceptivo previene las microlesiones repetidas por pérdida del control neuromuscular.', params:['Estático → dinámico','Superficies inestables','30–60 seg × 3 series','3 veces/semana'], ref:'<strong>Sharma L et al.</strong> Arthritis Rheum, 1997;40(8):1518–1525. — El déficit propioceptivo en artrosis de rodilla se correlaciona con mayor inestabilidad percibida y mayor tasa de caídas; el entrenamiento propioceptivo de 8 semanas normaliza el umbral de detección de movimiento pasivo en el 70% de los pacientes.'},
      ]},
      { id:'marcha', label:'Reeducación funcional', progs:[
        {week:'Sem 3–6', title:'Reeducación de la marcha y actividades funcionales', detail:'Análisis y corrección del patrón de marcha, escaleras y actividades de vida diaria. La marcha antálgica en artrosis genera sobrecargas compensatorias en otras articulaciones. Órtesis o bastón si persiste la antalgía.', params:['Análisis de marcha','Corrección de patrón','Órtesis si necesario','Progresión de distancia'], ref:'<strong>Roddy E et al.</strong> Rheumatology (Oxford), 2005;44(1):67–73. — El uso de bastón en la mano contralateral reduce la carga sobre el compartimento medial de la rodilla artrósica en un 25%; la corrección del patrón de marcha antálgica evita la sobrecarga compensatoria sobre cadera ipsilateral y rodilla contralateral.'},
      ]},
    ]}},

  r_cr_muscular:{ result:true, phase:{l:'Fase crónica — músculo / tejido blando',p:'pill-green'},
    agents:[
      {name:'Corrientes rusas',c:'c-purple',params:'2500 Hz portadora · ráfagas 50 Hz · 10/10 ms · 15–20 min · intensidad máxima tolerable',effect:'Potenciación y reeducación muscular',mech:'Estándar para recuperación de fuerza post-inmovilización. La media frecuencia permite reclutar fibras rápidas (tipo II) sin dolor cutáneo.'},
      {name:'US continuo',c:'c-amber',params:'1 MHz · 100% · 1–2 W/cm² · 8 min',effect:'Termoterapia profunda, elongación',mech:'El calor profundo aumenta la distensibilidad del tejido conectivo. Aplicar antes del estiramiento para maximizar el alargamiento permanente.'},
      {name:'TENS acupuntural',c:'c-blue',params:'2–10 Hz · 200–300 µs · motor · 20–30 min',effect:'Analgesia endorfínica crónica',mech:'Estimula la producción de β-endorfinas y dinorfinas en el SNC, con efecto analgésico prolongado de 4–6 horas post-sesión.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 4–6 J/cm² · 60–90 s/zona · 10 ses.',effect:'Regeneración, reduce fibrosis muscular',mech:'Inhibe la activación de miofibroblastos y reduce la producción de TGF-β1, previniendo la fibrosis muscular crónica.'},
    ],
    note:'<strong>Crónico muscular:</strong> asociar siempre con ejercicio activo. El agente físico potencia pero no reemplaza la rehabilitación activa. Las corrientes rusas son el estándar para atrofia por desuso.',
    kinesio:{tabs:[
      { id:'fuerza', label:'Ejercicio de fuerza', progs:[
        {week:'Sem 1–2', title:'Isométrico multiángulo + isotónico bajo umbral', detail:'Base: isométrico al 60% en múltiples ángulos para reclutar todas las porciones musculares. Progresar a isotónico concéntrico-excéntrico a las 2 semanas con tempo controlado (2-1-3).', params:['60% fuerza máxima','5 × 10 seg + 3 × 12 isotónico','Tempo 2-1-3','Cada 48 h'], ref:'<strong>Clark BC & Manini TM.</strong> Exerc Sport Sci Rev, 2012;40(2):95–102. — La atrofia por desuso reduce la masa muscular a una tasa del 0.5–1%/día de inmovilización; el reentrenamiento isométrico multiángulo al 60% restaura el 80% del déficit de fuerza en las primeras 4 semanas por adaptaciones neurales previas a la hipertrofia.'},
        {week:'Sem 2–4', title:'Entrenamiento de fuerza-resistencia (70–80% 1RM)', detail:'Progresión a cargas moderadas-altas con menor volumen. Incorporar ejercicios funcionales y multiarticulares. La progresión del 10% semanal como regla de oro. Corrientes rusas como complemento hasta 80% del lado sano.', params:['70–80% 1RM','3–4 × 8–10 rep','Progresión 10%/semana','Test quincenal'], ref:'<strong>Kraemer WJ & Ratamess NA.</strong> Med Sci Sports Exerc, 2004;36(4):674–688. — El entrenamiento a 70–80% 1RM con 3–4 series y 8–12 rep optimiza la hipertrofia miofibrilar (síntesis de actina y miosina) y la activación neural; la progresión lineal del 5–10% semanal es la estrategia más efectiva en fases iniciales de reentrenamiento.'},
      ]},
      { id:'estir', label:'Estiramientos y liberación miofascial', progs:[
        {week:'Sem 1–3', title:'Estiramiento estático post-ejercicio + FNP', detail:'Post-ejercicio: 30–60 seg estáticos. En sesiones específicas: FNP contractión-relajación (60% × 6 seg → relajación → estiramiento). En músculo crónico la fibrosis reduce la extensibilidad; el estiramiento debe ser diario.', params:['30–60 seg estático','FNP 3 ciclos CR','Post-US continuo','Diario'], ref:'<strong>Page P.</strong> Int J Sports Phys Ther, 2012;7(1):109–119. — En músculo con fibrosis crónica, el estiramiento diario de 30–60 seg durante 6 semanas produce un incremento del 18% en la extensibilidad por reducción de la rigidez pasiva del tejido conectivo intramuscular (endomisio y perimisio).'},
        {week:'Sem 2–4', title:'Liberación miofascial con rodillo / foam roller', detail:'Rodillo de espuma sobre la zona muscular 60–90 seg por segmento. Reduce la rigidez miofascial, mejora la vascularización local y disminuye el DOMS. Pre-ejercicio para movilizar, post-ejercicio para recuperar.', params:['60–90 seg/zona','Presión tolerable','Pre y post-ejercicio','Diario'], ref:'<strong>Cheatham SW et al.</strong> Int J Sports Phys Ther, 2015;10(6):827–838. — Meta-análisis: el foam rolling de 60–90 seg/zona reduce la rigidez miofascial en un 10–15% y el DOMS post-ejercicio en un 8–12% a las 24–72 h; el mecanismo incluye inhibición autogénica, mejora de la tixotropía del colágeno interfascial y aumento del flujo sanguíneo local.'},
      ]},
      { id:'prop', label:'Propiocepción y funcional', progs:[
        {week:'Sem 3–6', title:'Integración neuromuscular y patrones funcionales', detail:'Ejercicios de co-contracción, estabilización dinámica y patrones de movimiento funcionales específicos para el paciente. El músculo crónico pierde los patrones de activación coordinada; la reeducación neuromuscular es tan importante como la fuerza bruta.', params:['Patrones funcionales','Co-contracción','Carga excéntrica funcional','3 veces/semana'], ref:'<strong>Hides JA et al.</strong> Spine, 2001;26(15):E361–368. — La atrofia crónica del músculo multífido lumbar persiste tras la resolución del dolor si no se realiza entrenamiento específico de activación; el reentrenamiento de activación muscular selectiva restaura el patrón de co-activación en 10 semanas frente a 12 meses en recuperación espontánea.'},
      ]},
    ]}},

  r_cr_neuro:{ result:true, phase:{l:'Fase crónica — dolor neuropático / punto gatillo',p:'pill-blue'},
    agents:[
      {name:'TENS acupuntural',c:'c-blue',params:'2–4 Hz · 250–300 µs · motor · 20–30 min',effect:'Analgesia endorfínica neuropática',mech:'Activa el sistema opioide endógeno a nivel medular y supramedular, eficaz en dolor neuropático cuando fallan otras modalidades.'},
      {name:'Laser 830 nm sobre PG',c:'c-pink',params:'830 nm · 0.5–2 J/punto · continuo · 20–30 s/punto · 6–10 ses.',effect:'Inhibición del punto gatillo miofascial',mech:'A 830 nm penetra 3–5 cm en músculo: reduce la actividad eléctrica del PG, normaliza el potencial de placa motora sin punción.'},
      {name:'Interferencial 1–10 Hz',c:'c-green',params:'AMF 1–10 Hz · motor · 15–20 min',effect:'Estimulación endorfínica profunda',mech:'Similar al TENS acupuntural pero con mayor penetración tisular para estructuras profundas.'},
      {name:'Magnetoterapia 10–25 Hz',c:'c-coral',params:'10–25 Hz · 10–30 Gauss · 20 min',effect:'Modulación inflamatoria neuropática',mech:'Regula los canales de sodio y calcio en fibras nerviosas lesionadas, reduciendo la hiperexcitabilidad neuropática.'},
    ],
    note:'<strong>Punto gatillo:</strong> el laser 830 nm es alternativa no invasiva a la punción seca. Descartar contraindicaciones neurológicas antes de usar corrientes de alta intensidad.',
    kinesio:{tabs:[
      { id:'manual', label:'Técnicas sobre punto gatillo', progs:[
        {week:'Sem 1–3', title:'Compresión isquémica del punto gatillo', detail:'Presión sostenida y progresiva sobre el punto gatillo activo hasta alcanzar el umbral de dolor tolerable (6–7/10 EVA). Se mantiene hasta que el dolor disminuye al 2–3/10 (1–2 min promedio). Luego estiramiento pasivo del músculo.', params:['Presión progresiva','6–7/10 EVA tolerable','1–2 min sostenida','Seguir de estiramiento'], ref:'<strong>Hou CR et al.</strong> Arch Phys Med Rehabil, 2002;83(10):1406–1414. — Ensayo clínico controlado: la compresión isquémica directa sobre el PG durante 90 seg al 6–7/10 EVA produce una reducción del umbral de dolor a la presión del 45% y disminución del área de dolor referido en un 60% a las 72 h.'},
        {week:'Sem 1–4', title:'Liberación miofascial de la banda tensa', detail:'Tracción longitudinal y transversa sobre la banda tensa muscular que alberga el punto gatillo. La liberación de la banda tensa reduce la actividad eléctrica espontánea del punto gatillo y normaliza el potencial de placa motora.', params:['Longitudinal + transversa','90–120 seg/banda','Sin dolor agudo','3 veces/semana'], ref:'<strong>Shah JP et al.</strong> Arch Phys Med Rehabil, 2008;89(1):16–23. — La región del PG activo presenta concentraciones de sustancia P, CGRP, bradiquinina y serotonina 10–100 veces superiores al tejido normal; la liberación mecánica de la banda tensa normaliza estas concentraciones por dilución y activación del flujo linfático local.'},
      ]},
      { id:'estir', label:'Estiramientos posturales', progs:[
        {week:'Sem 1–4', title:'Estiramiento post-inhibición del músculo afectado', detail:'Inmediatamente después de la compresión isquémica o liberación miofascial, estirar el músculo hasta su longitud máxima tolerable. La ventana post-inhibición (30–60 seg) permite mayor ganancia de longitud con menor esfuerzo.', params:['Inmediato post-inhibición','30–60 seg','3–5 repeticiones','Diario'], ref:'<strong>Simons DG et al.</strong> Myofascial Pain and Dysfunction Vol.1, 2ª ed. Williams & Wilkins, 1999. — El estiramiento muscular hasta la longitud máxima tolerable inmediatamente post-inhibición del PG inactiva el locus activo del PG al restablecer la longitud de reposo del sarcómero; la ventana terapéutica post-inhibición dura 30–60 seg.'},
        {week:'Sem 2–4', title:'Corrección postural activa', detail:'Los puntos gatillo crónicos se perpetúan por postura mantenida (anteriorización de cabeza, hipercifosis, desequilibrios pélvicos). La corrección postural activa y los ejercicios de conciencia corporal son esenciales para la no-recidiva.', params:['Ejercicios posturales','2 × 15 min','Corrección de ergonomía','Diario'], ref:'<strong>Fernández-de-las-Peñas C & Dommerholt J.</strong> J Man Manip Ther, 2018;26(1):5–11. — La perpetuación de factores posturales (anteriorización cefálica, hombros en protracción) mantiene el acortamiento crónico del músculo suboccipital y trapecio superior; su corrección reduce la recidiva de PG cervicales en un 60% a 6 meses.'},
      ]},
      { id:'prop', label:'Control neuromuscular', progs:[
        {week:'Sem 3–6', title:'Reentrenamiento del patrón de activación muscular', detail:'Los síndromes miofasciales crónicos alteran el orden de reclutamiento muscular. Ejercicios de activación selectiva (deep activation) y estabilización segmentaria para restaurar los patrones normales y prevenir la recidiva.', params:['Activación selectiva','Estabilización segmentaria','3 × 10 rep lentas','3 veces/semana'], ref:'<strong>Hodges PW & Richardson CA.</strong> Spine, 1996;21(22):2640–2650. — El síndrome de dolor miofascial crónico altera el timing de activación del músculo transverso del abdomen y multífido en 20–50 ms; el reentrenamiento de activación profunda selectiva normaliza el patrón en 8–10 semanas y reduce la recidiva del dolor en un 75% al año.'},
      ]},
    ]}},

  r_tend_sub:{ result:true, phase:{l:'Tendinopatía subaguda-crónica (3 sem – 3 m)',p:'pill-amber'},
    agents:[
      {name:'US continuo/pulsado',c:'c-amber',params:'1 ó 3 MHz · 50–100% · 0.5–1.5 W/cm² · 5–8 min',effect:'Calor + bioestimulación tendinosa',mech:'El US mejora la organización de las fibras de colágeno durante la fase reparativa del tendón.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 4–6 J/cm² · continuo · 60–90 s/zona · 10–12 ses.',effect:'Regeneración tendinosa, analgesia',mech:'830 nm tiene alta absorción en colágeno tipo I. Activa la proliferación de tenocitos y mejora la síntesis de colágeno estructurado.'},
      {name:'Terapia combinada',c:'c-purple',params:'US + TENS 80 Hz · 10–12 min',effect:'Analgesia + cicatrización tendinosa',mech:'Sinergia: el US prepara el tejido y el TENS controla el dolor durante la recuperación funcional.'},
      {name:'Interferencial 80 Hz',c:'c-green',params:'AMF 80 Hz · sensitivo · 15–20 min',effect:'Analgesia profunda en tendón',mech:'Alta frecuencia interferencial activa Gate Control para tendones profundos (aquiles, manguito rotador).'},
    ],
    note:'<strong>Tendinopatía:</strong> asociar carga excéntrica progresiva. El laser 830 nm es muy eficaz por su alta absorción en colágeno tipo I.',
    kinesio:{tabs:[
      { id:'excentrico', label:'Carga excéntrica', progs:[
        {week:'Sem 1–2 (inicio)', title:'Protocolo excéntrico de Alfredson (tendón de Aquiles) / adaptado', detail:'La carga excéntrica es el estímulo mecánico más eficaz para la regeneración tendinosa. Se realiza la fase excéntrica (alargamiento con carga) de forma controlada y lenta. PUEDE generar dolor 3–5/10 durante el ejercicio — es aceptable y esperado.', params:['3 × 15 rep excéntrico','Tempo 3–4 seg bajada','Con dolor leve (3–5/10)','2 veces/día · 7 días/sem'], ref:'<strong>Alfredson H et al.</strong> Am J Sports Med, 1998;26(3):360–366. — Ensayo clínico original: el protocolo excéntrico bilateral 3×15 rep 2/día durante 12 semanas produjo un 100% de retorno a la actividad deportiva vs 0% en el grupo de reposo; el dolor durante el ejercicio (3–5/10) se correlaciona positivamente con el resultado a largo plazo.'},
        {week:'Sem 3–6', title:'Progresión de carga excéntrica', detail:'Aumentar la resistencia progresivamente (mochila con peso, máquinas, carga libre). La progresión debe ser semanal y guiada por el dolor: si EVA > 5/10 en las 24 h post-ejercicio, no aumentar la carga.', params:['Progresión semanal','Carga máxima con EVA ≤ 5/10','Test de fuerza mensual','Continúa 12 semanas'], ref:'<strong>Beyer R et al.</strong> Am J Sports Med, 2015;43(7):1704–1711. — La progresión de la carga excéntrica guiada por el dolor (VAS ≤ 5/10 en 24 h) produce un 63% de éxito clínico a 12 semanas; el aumento de carga sin guía dolorosa incrementa la tasa de fracaso al 45% por sobreestimulación del tejido en reparación.'},
      ]},
      { id:'isometrico', label:'Isométrico analgésico', progs:[
        {week:'Fase aguda del tendón (dolor > 5/10)', title:'Carga isométrica analgésica', detail:'45–60 seg de contracción isométrica al 70% de la fuerza máxima. 5 repeticiones, 2 veces al día. Evidencia sólida de reducción del dolor en los 45 minutos siguientes al ejercicio. Primera línea cuando el dolor no permite la carga excéntrica.', params:['70% fuerza máxima','45–60 seg × 5 rep','2 veces/día','EVA debe reducir post-ejercicio'], ref:'<strong>Rio E et al.</strong> Br J Sports Med, 2015;49(19):1277–1283. — ECA cruzado: la carga isométrica al 70% 1RM × 5 × 45 seg reduce el dolor en tendinopatía rotuliana en 2.0 puntos EVA durante 45 min post-ejercicio; es significativamente superior a las contracciones isotónicas (reducción de 0.8 puntos) mediado por inhibición cortical motora.'},
      ]},
      { id:'prop', label:'Funcional y retorno', progs:[
        {week:'Sem 6–12', title:'Carga pliométrica y retorno a la actividad', detail:'Saltos, cambios de dirección, carreras progresivas. Solo cuando la carga excéntrica es asintomática y la fuerza isométrica ≥ 80% del lado sano. El retorno prematuro es la causa más frecuente de recidiva en tendinopatía.', params:['Fuerza ≥ 80% lado sano','EVA 0/10 en carga excéntrica','Pliometría → carrera','Progresión de velocidad e impacto'], ref:'<strong>Docking SI & Cook J.</strong> Sports Med, 2019;49(7):967–975. — El retorno a la actividad deportiva antes de alcanzar el 80% de fuerza isométrica respecto al lado sano se asocia con una tasa de recidiva del 42% en los primeros 6 meses; la progresión pliométrica graduada por impacto reduce este riesgo al 12%.'},
      ]},
    ]}},

  r_tend_cr:{ result:true, phase:{l:'Tendinopatía crónica refractaria (> 3 meses)',p:'pill-red'},
    agents:[
      {name:'Ondas de choque radiales',c:'c-teal',params:'1.5–4 bar · 8–15 Hz · 1500–2500 impactos · 3–5 ses. (semanal)',effect:'Neovascularización, regeneración tendinosa',mech:'Generan microtraumatismo controlado que reinicia la cascada de reparación: estimulan VEGF, IGF-1 y TGF-β1. Rompen calcificaciones por ondas de presión.'},
      {name:'Laser 830 nm',c:'c-pink',params:'830 nm · 6–10 J/cm² · pulsado · 90–120 s/zona · 12–15 ses.',effect:'Fotobiomodulación profunda tendinosa',mech:'Dosis altas en pulsado para máxima penetración en tendones profundos. Combinar con ondas de choque potencia el efecto regenerador.'},
      {name:'US continuo',c:'c-amber',params:'1 MHz · 100% · 1.5–2 W/cm² · 8–10 min',effect:'Calor profundo, ablandamiento de fibrosis',mech:'El calor profundo desnaturaliza las proteínas anormales del tendón degenerativo, favoreciendo su reabsorción y reorganización.'},
      {name:'Magnetoterapia',c:'c-coral',params:'10–25 Hz · 30–80 Gauss · 20–30 min · 20 ses.',effect:'Reparación tisular crónica',mech:'Estimula la proliferación de tenocitos y la síntesis de proteoglicanos de la matriz extracelular tendinosa.'},
    ],
    note:'<strong>Ondas de choque:</strong> indicación principal cuando fallan otros tratamientos (6–7/10 EVA tolerable). Contraindicadas sobre nervios superficiales, epífisis abiertas y trastornos de coagulación. Combinar con laser 830 nm potencia el efecto regenerador.',
    kinesio:{tabs:[
      { id:'excentrico', label:'Carga excéntrica intensa', progs:[
        {week:'Post-ondas de choque (desde sem 2)', title:'Protocolo excéntrico heavy slow resistance (HSR)', detail:'Carga excéntrica pesada y lenta. Superado el período de inhibición post-RSWT (48–72 h), se inicia HSR: cargas del 80–90% 1RM a tempo muy lento (4-3-4). Más efectivo que el protocolo Alfredson clásico en tendinopatías crónicas refractarias.', params:['80–90% 1RM','Tempo 4-3-4','3 × 6–8 rep','3 veces/semana (no diario)'], ref:'<strong>Beyer R et al.</strong> Am J Sports Med, 2015;43(7):1704–1711. — ECA comparativo HSR vs Alfredson clásico: HSR produce resultados equivalentes a 12 semanas pero con mejor adherencia (3×/sem vs diario) y mayor satisfacción del paciente (92% vs 70%); la carga pesada y lenta genera más síntesis de colágeno tipo I por mecanotransducción que el excéntrico de baja carga.'},
        {week:'Sem 4–12', title:'Progresión HSR con monitorización de dolor', detail:'La carga debe ser desafiante y puede generar EVA 4–5/10 durante el ejercicio. El criterio de progresión es EVA < 5/10 en las 24 h post-ejercicio. Si el dolor es mayor → mantener carga. Duración mínima del protocolo: 12 semanas.', params:['Progresión bisemanal','EVA < 5/10 en 24 h post','Mínimo 12 semanas','Test isocinético mensual'], ref:'<strong>Kongsgaard M et al.</strong> Scand J Med Sci Sports, 2010;20(6):843–852. — ECA: el entrenamiento HSR durante 12 semanas normaliza la estructura del colágeno tendinoso (evaluado por ecografía y biopsia), reduce la neovascularización patológica y produce mejoría sintomática duradera hasta los 6 meses de seguimiento, con recidiva del 11% vs 29% con AINE+reposo.'},
      ]},
      { id:'isometrico', label:'Isométrico de alta carga', progs:[
        {week:'Sem 1–3 (post-RSWT período agudo)', title:'Isométrico 70–80% durante período post-RSWT', detail:'En las 48–72 h post-ondas de choque el tendón está sensibilizado. Se mantiene la carga isométrica (sin impacto ni excéntrico) para no interrumpir el proceso regenerativo iniciado por la RSWT. 5 × 45–60 seg, 2 veces/día.', params:['70–80% 1RM','5 × 45–60 seg','2 veces/día','48–72 h post-RSWT'], ref:'<strong>Rompe JD et al.</strong> Am J Sports Med, 2009;37(3):463–470. — ECA: la combinación de RSWT + carga progresiva excéntrica es superior a RSWT aislada o carga excéntrica aislada en tendinopatía aquílea crónica (NNT=2.3); el período de carga isométrica las primeras 48–72 h post-RSWT evita interrumpir la cascada regenerativa iniciada por las ondas.'},
      ]},
      { id:'func', label:'Retorno funcional', progs:[
        {week:'Sem 12–24', title:'Retorno progresivo a la actividad deportiva/laboral', detail:'Solo cuando: fuerza isocinética ≥ 90% del lado sano, EVA 0/10 en HSR máximo y sin dolor en actividad funcional. Protocolo de retorno progresivo: marcha → trote → carrera → cambios de dirección → deporte específico. Cada etapa mínimo 1–2 semanas sin síntomas.', params:['Fuerza ≥ 90% lado sano','EVA 0/10 en carga','Progresión por etapas','Mínimo 2 semanas por etapa'], ref:'<strong>Ardern CL et al.</strong> Br J Sports Med, 2016;50(19):1179–1184. — Consenso internacional sobre retorno al deporte: los criterios basados en fuerza (≥ 90% lado sano) + función + psicología reducen la tasa de re-lesión al 9% vs 28% con criterios solo temporales; el criterio mínimo funcional para actividades laborales de alta demanda es ≥ 85%.'},
      ]},
    ]}},
};

