/* ===== KINESIOTERAPIA DATA ===== */
const KINE_CATS = [
  { id:'manual', label:'Técnicas manuales', icon:'🤲', color:'coral' },
  { id:'movil',  label:'Movilización articular', icon:'🔄', color:'blue' },
  { id:'ejerc',  label:'Ejercicio terapéutico', icon:'💪', color:'green' },
  { id:'estir',  label:'Estiramientos', icon:'🧘', color:'amber' },
  { id:'prop',   label:'Propiocepción', icon:'⚖️', color:'purple' },
  { id:'marcha', label:'Marcha y funcional', icon:'🚶', color:'teal' },
];

const KINE_TECHS = {
  manual: [
    { title:'Masaje transverso profundo (Cyriax)',
      sub:'Fricción transversa al eje de las fibras de colágeno',
      desc:'Técnica de fricción profunda aplicada perpendicularmente a las fibras de colágeno del tejido lesionado. El objetivo es orientar el colágeno neoformado, romper adherencias patológicas y estimular la síntesis de colágeno funcional. Genera una inflamación controlada y local que reactiva el proceso de reparación en tejidos crónicos.',
      phases:[
        { phase:'Subaguda (sem 2–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Fricción transversa perilesional, sobre tejido íntegro ya cerrado. 5–10 min, presión moderada tolerable, cada 48 h. Objetivo: orientar el colágeno en formación.',
          params:['Transverso al eje del colágeno','5–10 min','Cada 48 h','Sobre tejido cerrado'] },
        { phase:'Crónica (sem 4+)', pill:'pill-green', col:'kp-phase-green',
          detail:'Fricción directa sobre la cicatriz madura. 8–10 min, 3 veces/semana. Puede ser levemente molesta. Post-calentamiento (US continuo) para mayor eficacia.',
          params:['Directo sobre cicatriz','8–10 min','3 veces/semana','Post-US continuo'] },
      ],
      ref:'<strong>Cyriax J.</strong> Textbook of Orthopaedic Medicine Vol.2, 11ª ed. Baillière Tindall, 1984. — La fricción transversa genera cizallamiento que rompe los enlaces cruzados anormales del colágeno cicatrizal e incrementa la producción de colágeno tipo I orientado en un 30% vs control.' },

    { title:'Liberación miofascial (Barnes)',
      sub:'Tracción suave y sostenida del sistema fascial',
      desc:'Técnica de presión mínima (5–7 gramos) aplicada sostenidamente sobre la fascia hasta obtener el "release" (sensación de ablandamiento o cesión). Actúa sobre la viscoelasticidad del colágeno interfascial y sobre los mecanorreceptores de Ruffini en la fascia superficial, reduciendo el tono simpático y la hipertonía refleja.',
      phases:[
        { phase:'Aguda tardía (día 3+)', pill:'pill-red', col:'kp-phase-red',
          detail:'Tracción fascial suave perimetral a la zona. Presión mínima 5 g, 90–120 seg, dirección de restricción. Sin dolor.',
          params:['Presión 5 g','90–120 seg','Sin fuerza mecánica','Perimetral a lesión'] },
        { phase:'Subaguda y crónica', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Trabajo directo sobre la zona de restricción fascial. Hasta 3–5 min por zona. Combinar con movimiento activo asistido del paciente para mayor efectividad.',
          params:['Tracción sostenida','3–5 min/zona','Con movimiento activo','3 veces/semana'] },
      ],
      ref:'<strong>Barnes JF.</strong> Myofascial Release: The Search for Excellence. Rehabilitation Services, 1990. — El release miofascial ocurre a los 90–120 seg por reorganización viscoelástica del colágeno interfascial; no requiere fuerza mecánica significativa.' },

    { title:'Inhibición de puntos gatillo (Travell)',
      sub:'Compresión isquémica sostenida sobre el PG activo',
      desc:'Presión directa progresiva sobre el punto gatillo activo hasta alcanzar el umbral de dolor tolerable (6–7/10 EVA). Se mantiene hasta que el dolor cede al 2–3/10. Activa el reflejo inhibitorio del OTG y normaliza el potencial de placa motora disfuncional del punto gatillo. Seguir siempre de estiramiento.',
      phases:[
        { phase:'Subaguda (sem 1–3)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Presión progresiva sostenida al 6–7/10 EVA hasta reducción al 2–3/10. 60–90 seg, 3–5 puntos por sesión. Seguir de estiramiento pasivo del músculo.',
          params:['6–7/10 EVA tolerable','60–90 seg/punto','3–5 puntos/sesión','Seguir de estiramiento'] },
        { phase:'Crónica (sem 1–6)', pill:'pill-green', col:'kp-phase-green',
          detail:'Compresión + liberación de banda tensa + estiramiento en una secuencia integrada. 3 veces/semana. Asociar corrección postural activa para prevenir recidiva.',
          params:['Compresión + banda tensa + estiramiento','3 veces/semana','Corrección postural asociada'] },
      ],
      ref:'<strong>Hou CR et al.</strong> Arch Phys Med Rehabil, 2002;83:1406–1414. DOI: 10.1053/apmr.2002.34815 — La compresión isquémica al 6–7/10 EVA reduce el umbral de dolor a la presión en un 45% y el área de dolor referido en un 60% a las 72 h.' },

    { title:'Drenaje linfático manual (Vodder)',
      sub:'Vaciado ganglionar proximal → captura del edema distal',
      desc:'Secuencia sistematizada: vaciado ganglionar proximal → trabajo territorial → anastomosis → captura en zona edematosa. La dirección siempre es proximal al flujo linfático natural. Presión máxima 30–40 mmHg. Siempre continuar con vendaje multicapa post-sesión para mantener el efecto drenante.',
      phases:[
        { phase:'Aguda (día 1–7)', pill:'pill-red', col:'kp-phase-red',
          detail:'Vaciado ganglionar proximal + trabajo territorial. Presión 20–30 mmHg, 15–20 min, 1–2 veces/día. Extremidad elevada durante la sesión.',
          params:['20–30 mmHg','Proximal al flujo','15–20 min','1–2 veces/día'] },
        { phase:'Subaguda (sem 1–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Protocolo completo CDT fase I: DLM + vendaje multicapa + ejercicio de bomba + cuidado de piel. 20–30 min, vendaje post-sesión 20–23 h/día.',
          params:['20–30 min DLM','Vendaje multicapa post-sesión','Ejercicio de bomba','20–23 h/día vendaje'] },
      ],
      ref:'<strong>ISL Consensus.</strong> Lymphology, 2020;53(1):3–19. — El DLM + vendaje multicapa (CDT fase I) reduce el volumen del edema en un 40–70% en 3–4 semanas; el DLM aislado pierde el 50% del efecto en 24 h sin vendaje.' },

    { title:'Masaje de effleurage / petrissage',
      sub:'Deslizamiento superficial y amasamiento muscular',
      desc:'Effleurage: deslizamientos suaves y rítmicos en dirección proximal, presión superficial. Actúa sobre receptores cutáneos (Meissner, Ruffini) produciendo inhibición descendente del dolor y mejora del retorno venoso superficial. Petrissage: amasamiento del tejido muscular que mejora la circulación local, reduce la rigidez y moviliza el tejido intersticial.',
      phases:[
        { phase:'Aguda (día 3+)', pill:'pill-red', col:'kp-phase-red',
          detail:'Solo effleurage superficial, perimetral a la zona de lesión. 5–8 min, presión mínima. Evitar el sitio exacto de lesión.',
          params:['Perimetral a lesión','Presión superficial','5–8 min','Dirección proximal'] },
        { phase:'Subaguda y crónica', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Effleurage + petrissage sobre el vientre muscular. 10–15 min. Pre-ejercicio para movilizar o post-ejercicio para recuperación. Puede preceder a otros agentes físicos.',
          params:['Effleurage + petrissage','10–15 min','Pre o post-ejercicio','3 veces/semana'] },
      ],
      ref:'<strong>Weerapong P et al.</strong> Sports Med, 2005;35(3):235–256. DOI: 10.2165/00007256-200535030-00004 — El effleurage estimula receptores cutáneos de bajo umbral activando inhibición descendente; el petrissage incrementa el flujo sanguíneo local en un 12% y reduce el DOMS en un 8–10%.' },
  ],

  movil: [
    { title:'Movilización grados I–II (Maitland) — analgesia',
      sub:'Oscilaciones rítmicas en rango libre de dolor',
      desc:'Oscilaciones de pequeña amplitud (grado I) o de mayor amplitud sin alcanzar la resistencia tisular (grado II), aplicadas en la dirección de movimiento deseada. Activan mecanorreceptores articulares de bajo umbral (tipo I de Ruffini y tipo II de Pacini) que inhiben la transmisión nociceptiva a nivel medular (Gate Control). Indicadas cuando el dolor es el síntoma principal limitante.',
      phases:[
        { phase:'Aguda (día 1–7)', pill:'pill-red', col:'kp-phase-red',
          detail:'Oscilaciones grado I dentro del rango libre. 2–3 series × 30 oscilaciones. Ritmo lento-moderado. Sin dolor durante la técnica.',
          params:['Grado I','30 oscilaciones/serie','2–3 series','Sin dolor'] },
        { phase:'Subaguda (sem 1–3)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Oscilaciones grado II hasta el inicio de resistencia (R1). 3 series × 30 oscilaciones. Ritmo moderado. EVA < 4/10 durante la técnica.',
          params:['Grado II hasta R1','3 × 30 oscilaciones','Ritmo moderado','EVA < 4/10'] },
      ],
      ref:'<strong>Zusman M.</strong> Phys Ther Rev, 2011;16(5):353–360. DOI: 10.1179/1743288X11Y.0000000021 — Las oscilaciones grado I–II activan mecanorreceptores tipo I y II articulares activando inhibición descendente por vías noradrenérgicas y serotoninérgicas desde el troncoencéfalo.' },

    { title:'Movilización grados III–IV (Maitland) — ROM',
      sub:'Oscilaciones en el rango final para recuperar amplitud',
      desc:'Oscilaciones de gran amplitud que alcanzan la resistencia tisular (grado III) o movimientos de pequeña amplitud en el límite del rango (grado IV). Generan estiramiento mecánico del tejido capsular y ligamentoso, aumentando el ROM. Aplicar siempre tras calentamiento previo (US continuo o termoterapia superficial) para maximizar la extensibilidad del colágeno.',
      phases:[
        { phase:'Subaguda tardía (sem 2–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Grado III post-calor. 3 series × 20 oscilaciones. Límite: EVA 4–5/10 tolerable. Aplicar inmediatamente post-US continuo o calor superficial.',
          params:['Grado III','Post-calor (US/IR)','3 × 20 oscilaciones','EVA 4–5/10'] },
        { phase:'Crónica (sem 3+)', pill:'pill-green', col:'kp-phase-green',
          detail:'Grado IV para cápsula rígida. 3–4 series × 15 oscilaciones. Combinado con tracción de Kaltenborn para mayor efectividad en pérdida de juego articular.',
          params:['Grado IV','Cápsula rígida','3–4 × 15 oscilaciones','Combinar con Kaltenborn'] },
      ],
      ref:'<strong>Brosseau L et al.</strong> Cochrane Database Syst Rev, 2011;(2):CD004683. DOI: 10.1002/14651858.CD004683.pub2 — La movilización grado III–IV con termoterapia previa produce una ganancia de ROM un 35% superior a la movilización sin calor por mayor extensibilidad del colágeno capsular.' },

    { title:'Tracción articular grado II–III (Kaltenborn)',
      sub:'Desplazamiento perpendicular al plano de tratamiento',
      desc:'Desplazamiento articular en dirección perpendicular al plano de tratamiento. Grado II elimina la carga articular y activa mecanorreceptores de baja frecuencia (efecto analgésico). Grado III genera elongación viscoelástica sostenida del tejido capsular-ligamentoso para recuperar ROM. Aplicar de 10 a 30 segundos sostenidos por serie.',
      phases:[
        { phase:'Subaguda (analgesia)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Tracción grado II. Descompresión articular 10–20 seg, 3–5 repeticiones. Alivio del dolor intraarticular. Aplicar al inicio de la sesión.',
          params:['Grado II','10–20 seg sostenida','3–5 rep','Inicio de sesión'] },
        { phase:'Crónica (ROM)', pill:'pill-green', col:'kp-phase-green',
          detail:'Tracción grado III. 20–30 seg sostenida, 3–5 repeticiones, cada 48 h. Objetivo: elongar el tejido capsular rígido en artrosis o capsulitis adhesiva.',
          params:['Grado III','20–30 seg sostenida','3–5 rep','Cada 48 h'] },
      ],
      ref:'<strong>Kaltenborn FM.</strong> Manual Mobilization of the Joints, 8ª ed. Norli, 2014. — La tracción grado II reduce la presión intraarticular y activa mecanorreceptores de bajo umbral inhibiendo la transmisión del dolor; la tracción grado III produce elongación viscoelástica sostenida de la cápsula articular.' },
  ],

  ejerc: [
    { title:'Ejercicio isométrico',
      sub:'Contracción muscular estática sin movimiento articular',
      desc:'Contracción muscular sin cambio de longitud ni movimiento articular. Permite mantener la activación neuromuscular y el trofismo muscular sin generar estrés mecánico sobre el tejido en reparación. En tendinopatía, las contracciones isométricas de alta carga (70% 1RM) producen analgesia cortical inmediata de 45 minutos de duración.',
      phases:[
        { phase:'Aguda (día 1+)', pill:'pill-red', col:'kp-phase-red',
          detail:'Isométrico submáximo 40–50%. 10 seg contracción / 10 seg reposo, 3 × 10 rep, 1–2 veces/día. Sin dolor. Posición de reposo articular.',
          params:['40–50% fuerza máx','10 seg / 10 seg reposo','3 × 10 rep','Sin dolor'] },
        { phase:'Subaguda–Crónica', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Isométrico analgésico en tendinopatía: 70% 1RM × 5 × 45–60 seg, 2 veces/día. En rehabilitación general: multiángulo 60–70%, 5 ángulos, cada 48 h.',
          params:['60–70% 1RM','45–60 seg × 5 rep','2 veces/día','Múltiples ángulos'] },
      ],
      ref:'<strong>Rio E et al.</strong> Br J Sports Med, 2015;49(19):1277–1283. DOI: 10.1136/bjsports-2014-094386 — Las contracciones isométricas al 70% 1RM reducen el dolor en tendinopatía rotuliana en 2.0 puntos EVA durante 45 min mediado por inhibición cortical motora (MEP).' },

    { title:'Ejercicio isotónico concéntrico-excéntrico',
      sub:'Movimiento dinámico con resistencia externa progresiva',
      desc:'Trabajo muscular dinámico con resistencia. El componente excéntrico (alargamiento con carga) es superior al concéntrico para hipertrofia, protección tendinosa y corrección de desequilibrios musculares. El tempo controlado (2-1-3: 2 seg subida / 1 pausa / 3 seg bajada) maximiza el tiempo bajo tensión y la síntesis proteica.',
      phases:[
        { phase:'Subaguda (sem 1–3)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Baja carga 30–50% 1RM. 3 × 12–15 rep. Tempo lento (2-1-3). Carga progresiva semanal. EVA < 3/10 durante el ejercicio.',
          params:['30–50% 1RM','3 × 12–15 rep','Tempo 2-1-3','EVA < 3/10'] },
        { phase:'Crónica (sem 3+)', pill:'pill-green', col:'kp-phase-green',
          detail:'70–80% 1RM. 3–4 × 8–10 rep. Progresión 10%/semana. Ejercicios multiarticulares funcionales. Test de fuerza quincenal.',
          params:['70–80% 1RM','3–4 × 8–10 rep','Progresión 10%/sem','Test quincenal'] },
      ],
      ref:'<strong>Roig M et al.</strong> Br J Sports Med, 2009;43(8):556–568. DOI: 10.1136/bjsm.2008.051417 — El entrenamiento excéntrico produce un 10% más de ganancia de fuerza máxima y un 20% más de hipertrofia que el concéntrico aislado, con menor coste metabólico y mayor efecto sobre la rigidez tendinosa.' },

    { title:'Protocolo excéntrico (Alfredson / HSR)',
      sub:'Carga excéntrica progresiva para tendinopatía',
      desc:'Protocolo Alfredson clásico: 3×15 rep excéntrico, 2 veces/día, 7 días/semana, 12 semanas. El dolor moderado (3–5/10) durante el ejercicio es aceptable y predice buen resultado. Heavy Slow Resistance (HSR): 80–90% 1RM, tempo 4-3-4, 3 veces/semana. Superior en adherencia y para tendinopatías crónicas refractarias.',
      phases:[
        { phase:'Tendinopatía subaguda (sem 2–6)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Alfredson: 3 × 15 rep excéntrico, tempo 3–4 seg bajada, con dolor 3–5/10, 2/día × 7 días/semana durante 12 semanas.',
          params:['3 × 15 rep excéntrico','Dolor 3–5/10 tolerable','2 veces/día','12 semanas mínimo'] },
        { phase:'Tendinopatía crónica refractaria', pill:'pill-red', col:'kp-phase-red',
          detail:'HSR: 80–90% 1RM, tempo 4-3-4, 3 × 6–8 rep, 3 veces/semana. Post-ondas de choque desde sem 2. EVA < 5/10 en 24 h = criterio de progresión.',
          params:['80–90% 1RM','Tempo 4-3-4','3 × 6–8 rep','3 veces/semana'] },
      ],
      ref:'<strong>Alfredson H et al.</strong> Am J Sports Med, 1998;26(3):360–366. DOI: 10.1177/03635465980260031601 — 100% retorno deportivo con protocolo excéntrico vs 0% en grupo control. El dolor moderado durante el ejercicio predice buen resultado. / <strong>Kongsgaard M et al.</strong> Scand J Med Sci Sports, 2010;20(6):843–852. DOI: 10.1111/j.1600-0838.2009.01015.x — HSR normaliza la estructura del colágeno tendinoso y produce mejoría duradera hasta 6 meses.' },

    { title:'Entrenamiento de fuerza-resistencia muscular',
      sub:'Recuperación de fuerza post-lesión o inmovilización',
      desc:'Protocolo progresivo para recuperar la masa y fuerza muscular perdida por desuso o inmovilización. La atrofia muscular ocurre a una tasa del 0.5–1% por día de inmovilización. El reentrenamiento comienza con isométrico multiángulo → isotónico baja carga → carga moderada-alta (70–80% 1RM) siguiendo la regla de progresión del 10% semanal.',
      phases:[
        { phase:'Subaguda (sem 1–3)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Isométrico multiángulo 60% + isotónico baja carga. 3 × 12 rep, tempo 2-1-3, cada 48 h. Corrientes rusas como complemento si la contracción voluntaria es insuficiente.',
          params:['60% isométrico multiángulo','3 × 12 isotónico','Corrientes rusas complemento','Cada 48 h'] },
        { phase:'Crónica (sem 3+)', pill:'pill-green', col:'kp-phase-green',
          detail:'70–80% 1RM, 3–4 × 8–10 rep, progresión 10%/semana. Test de fuerza quincenal. Alta al 80–90% del lado sano.',
          params:['70–80% 1RM','3–4 × 8–10 rep','Progresión 10%/sem','Alta: 80–90% lado sano'] },
      ],
      ref:'<strong>Kraemer WJ & Ratamess NA.</strong> Med Sci Sports Exerc, 2004;36(4):674–688. DOI: 10.1249/01.MSS.0000127355.35472.59 — Cargas 70–80% 1RM con 3–4 series y 8–12 rep optimizan la hipertrofia miofibrilar. / <strong>Clark BC & Manini TM.</strong> Exerc Sport Sci Rev, 2012;40(2):95–102. DOI: 10.1097/JES.0b013e31825b4be6 — El isométrico multiángulo al 60% restaura el 80% del déficit de fuerza en 4 semanas por adaptaciones neurales.' },
  ],

  estir: [
    { title:'Estiramiento estático pasivo',
      sub:'Posición de elongación mantenida sin rebote',
      desc:'Posición de elongación máxima tolerable mantenida estáticamente. Reduce la rigidez músculotendinosa entre un 5–10% por sesión. La duración óptima es de 30–60 segundos; duraciones mayores no producen beneficio adicional significativo. El estiramiento diario acumula sus efectos; sin mantenimiento, la ganancia se pierde en 4–6 semanas.',
      phases:[
        { phase:'Aguda tardía (día 3–7)', pill:'pill-red', col:'kp-phase-red',
          detail:'Hasta el inicio de la resistencia (R1), sin superar el umbral de dolor. 20–30 seg, 3 rep. Objetivo: reducir hipertonía refleja, no ganar amplitud.',
          params:['Hasta R1','20–30 seg','3 rep','EVA < 3/10'] },
        { phase:'Subaguda y crónica', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Hasta el final del ROM disponible. 30–60 seg, 3–5 rep, 1–2 veces/día. En músculo con fibrosis: aplicar post-US continuo para plastificación.',
          params:['30–60 seg','3–5 rep','1–2 veces/día','Post-calor en crónico'] },
      ],
      ref:'<strong>Bandy WD & Irion JM.</strong> Phys Ther, 1994;74(9):845–852. DOI: 10.1093/ptj/74.9.845 — 30 seg es la duración mínima eficaz para incrementar el ROM; no hay beneficio adicional al superar los 60 seg. / <strong>Behm DG & Chaouachi A.</strong> Eur J Appl Physiol, 2011;111(11):2633–2651. DOI: 10.1007/s00421-011-1879-2 — El estiramiento diario de 30–60 seg restaura la extensibilidad perdida en 2–3 semanas de entrenamiento continuo.' },

    { title:'FNP Contracción-Relajación (CR)',
      sub:'Contracción isométrica + relajación + estiramiento progresivo',
      desc:'Contracción isométrica del músculo a elongar al 50–60% de la fuerza máxima durante 6 segundos, seguida de relajación de 2–3 seg y estiramiento pasivo progresivo. La inhibición autogénica post-contracción del OTG (órgano tendinoso de Golgi) permite mayor elongación con menor activación del reflejo miotático. Produce un 10% más de ganancia de ROM que el estiramiento estático.',
      phases:[
        { phase:'Subaguda (sem 2–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Contracción 50–60% × 6 seg → relajación 2–3 seg → estiramiento pasivo hasta nuevo límite. 3–4 ciclos por sesión, cada 48 h.',
          params:['Contracción 50–60%','6 seg + relajación','3–4 ciclos','Cada 48 h'] },
        { phase:'Crónica', pill:'pill-green', col:'kp-phase-green',
          detail:'Contracción 60–70% × 6 seg → relajación → estiramiento más allá del ROM previo. 4–5 ciclos. Post-US continuo para maximizar la plastificación.',
          params:['60–70% contracción','Post-US continuo','4–5 ciclos','3 veces/semana'] },
      ],
      ref:'<strong>Sharman MJ et al.</strong> Sports Med, 2006;36(11):929–939. DOI: 10.2165/00007256-200636110-00002 — FNP-CR supera al estiramiento estático en ganancia de ROM en un 10% adicional por sesión; la inhibición autogénica del OTG post-contracción isométrica permite alcanzar mayores longitudes sin activación del reflejo miotático. / <strong>Hindle KB et al.</strong> J Hum Kinet, 2012;31:105–113. DOI: 10.2478/v10078-012-0011-1' },

    { title:'FNP Contracción-Relajación-Contracción del agonista (CRAC)',
      sub:'Máxima ganancia de ROM por inhibición recíproca',
      desc:'Variante avanzada de FNP: contracción isométrica del músculo a elongar (6 seg) → relajación → contracción activa del músculo antagonista durante el estiramiento. La contracción del antagonista activa la inhibición recíproca (ley de Sherrington), relajando aún más el músculo target. Es la técnica de estiramiento con mayor ganancia de ROM pero requiere mayor coordinación.',
      phases:[
        { phase:'Subaguda tardía – Crónica', pill:'pill-green', col:'kp-phase-green',
          detail:'CR del músculo target (6 seg) → relajación → contracción activa del antagonista durante el estiramiento pasivo. 3–4 ciclos, cada 48–72 h.',
          params:['CR del target','Contracción activa antagonista','3–4 ciclos','Cada 48–72 h'] },
      ],
      ref:'<strong>Sharman MJ et al.</strong> Sports Med, 2006;36(11):929–939. DOI: 10.2165/00007256-200636110-00002 — La técnica CRAC combina inhibición autogénica + inhibición recíproca, produciendo la mayor ganancia de ROM de todas las técnicas de estiramiento; requiere al menos 3–4 semanas de práctica para dominar la coordinación.' },

    { title:'Estiramiento dinámico (balístico controlado)',
      sub:'Oscilaciones activas controladas en el rango de movimiento',
      desc:'Movimientos dinámicos activos que llevan el segmento hacia el límite del ROM y regresan sin rebote forzado. Activa el patrón de reclutamiento muscular dinámico, mejora la coordinación y el rango funcional. Indicado como calentamiento previo al ejercicio. No recomendado en fase aguda ni como primera técnica en músculo frío.',
      phases:[
        { phase:'Calentamiento pre-ejercicio (desde sem 3)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'10–15 repeticiones por dirección, amplitud progresiva sin dolor, controlado (sin rebote brusco). 2–3 series. Precedido de calor general (5–10 min aeróbico).',
          params:['10–15 rep/dirección','Sin rebote brusco','2–3 series','Post-calentamiento general'] },
      ],
      ref:'<strong>Behm DG & Chaouachi A.</strong> Eur J Appl Physiol, 2011;111(11):2633–2651. DOI: 10.1007/s00421-011-1879-2 — El estiramiento dinámico previo al ejercicio no reduce la fuerza ni la potencia (a diferencia del estático > 60 seg) y mejora el rendimiento muscular en un 4–8% al activar el reflejo miotático de forma controlada.' },
  ],

  prop: [
    { title:'Entrenamiento propioceptivo básico (estático)',
      sub:'Equilibrio estático en superficie estable e inestable',
      desc:'Ejercicios de equilibrio estático en una extremidad o en bipedestación inestable. El objetivo es restablecer los mecanorreceptores articulares y musculares dañados por la lesión, que transmiten información de posición y movimiento al SNC. El déficit propioceptivo persiste incluso después de la resolución del dolor, predisponiendo a re-lesiones.',
      phases:[
        { phase:'Subaguda (sem 2–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Equilibrio estático monopodal en superficie firme: ojos abiertos → ojos cerrados. 30 seg × 3 series, 3 veces/semana. Progresión: añadir movimiento de MMSS.',
          params:['Monopodal en superficie firme','Ojos abiertos → cerrados','30 seg × 3 series','3 veces/semana'] },
        { phase:'Crónica temprana (sem 3–6)', pill:'pill-green', col:'kp-phase-green',
          detail:'Monopodal sobre superficie inestable (foam, bosu, cama elástica). 30–60 seg × 3 series. Añadir perturbaciones manuales externas.',
          params:['Superficie inestable','30–60 seg × 3 series','Perturbaciones externas','3 veces/semana'] },
      ],
      ref:'<strong>Risberg MA et al.</strong> Am J Sports Med, 2007;35(5):723–730. DOI: 10.1177/0363546506296987 — El entrenamiento propioceptivo progresivo reduce el riesgo de re-lesión en un 51% en atletas post-esguince al restaurar los tiempos de reacción muscular refleja. / <strong>Zech A et al.</strong> J Athl Train, 2010;45(5):522–536. DOI: 10.4085/1062-6050-45.5.522 — Meta-análisis: reduce la incidencia de lesiones deportivas en un 35%.' },

    { title:'Control neuromuscular dinámico',
      sub:'Estabilización dinámica y co-activación muscular',
      desc:'Ejercicios que requieren activación muscular coordinada en condiciones de inestabilidad o perturbación. Trabaja la co-contracción de agonistas y antagonistas, los patrones de activación muscular refleja y la estabilidad articular dinámica. Es la progresión natural desde el equilibrio estático hacia el movimiento funcional.',
      phases:[
        { phase:'Subaguda tardía (sem 3–6)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Co-contracción en superficie inestable + perturbaciones manuales. Sentadilla monopodal con control de valgo. 3 × 30–60 seg o 3 × 10 rep.',
          params:['Co-contracción','Perturbaciones manuales','3 × 30–60 seg','3 veces/semana'] },
        { phase:'Crónica (sem 5+)', pill:'pill-green', col:'kp-phase-green',
          detail:'Ejercicios de agilidad, cambios de dirección controlados, desaceleración. Específicos para la actividad del paciente. Solo cuando EVA 0/10 en ejercicio de fuerza.',
          params:['Agilidad controlada','Cambios de dirección','EVA 0/10 previo','Específico al paciente'] },
      ],
      ref:'<strong>Hodges PW & Richardson CA.</strong> Spine, 1996;21(22):2640–2650. DOI: 10.1097/00007632-199611150-00005 — La lesión altera el timing de activación del transverso y multífido en 20–50 ms; el reentrenamiento neuromuscular selectivo normaliza el patrón en 8–10 semanas.' },

    { title:'Activación selectiva muscular profunda',
      sub:'Reentrenamiento de la musculatura estabilizadora profunda',
      desc:'Técnica de activación consciente y selectiva de los músculos estabilizadores profundos (transverso del abdomen, multífido, suelo pélvico, rotadores profundos de cadera, manguito rotador). Requiere contracción de baja intensidad (30–40% de la MVIC), mantenida y sin sustitución por músculos superficiales. Base del entrenamiento de estabilidad segmentaria.',
      phases:[
        { phase:'Subaguda y crónica (sem 2+)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Contracción selectiva 30–40% MVIC, mantenida 10 seg, 10 rep × 3 series. Sin apnea. Progresión: mismo ejercicio en posiciones más desafiantes (supino → sentado → bípedo).',
          params:['30–40% MVIC','10 seg × 10 rep × 3 series','Sin apnea','Progresión de posición'] },
      ],
      ref:'<strong>Hides JA et al.</strong> Spine, 2001;26(15):E361–368. DOI: 10.1097/00007632-200108010-00004 — La atrofia del multífido persiste tras la resolución del dolor sin entrenamiento específico; el reentrenamiento selectivo restaura el volumen en 10 semanas vs 12 meses de recuperación espontánea.' },
  ],

  marcha: [
    { title:'Reeducación del patrón de marcha',
      sub:'Análisis y corrección biomecánica de la marcha',
      desc:'Evaluación observacional o instrumental del ciclo de marcha para identificar desviaciones compensatorias secundarias a la lesión (marcha antálgica, Trendelenburg, equino, circunducción). La corrección progresiva de estas alteraciones previene sobrecargas en articulaciones adyacentes. Incluye trabajo de apoyo plantar, longitud de paso, velocidad y simetría.',
      phases:[
        { phase:'Subaguda (sem 2–4)', pill:'pill-amber', col:'kp-phase-amber',
          detail:'Marcha con asistencia (bastón si necesario). Análisis de paso, corrección de patrón antálgico. Superficie plana, distancias progresivas. 15–30 min, 2 veces/día.',
          params:['Asistencia si necesaria','15–30 min','Superficie plana','Corrección de patrón antálgico'] },
        { phase:'Crónica (sem 4+)', pill:'pill-green', col:'kp-phase-green',
          detail:'Marcha sin asistencia en superficies variadas, escaleras, rampas. Análisis de cadencia y longitud de paso. Retiro progresivo de órtesis si se usaron.',
          params:['Superficies variadas','Escaleras y rampas','Cadencia y longitud de paso','Retiro progresivo de órtesis'] },
      ],
      ref:'<strong>Roddy E et al.</strong> Rheumatology (Oxford), 2005;44(1):67–73. DOI: 10.1093/rheumatology/keh399 — El bastón contralateral reduce la carga articular en un 25%; la corrección de la marcha antálgica evita la sobrecarga compensatoria sobre articulaciones adyacentes.' },

    { title:'Entrenamiento funcional específico',
      sub:'Patrones de movimiento propios de la actividad del paciente',
      desc:'Reproducción progresiva de los patrones de movimiento propios de la actividad laboral, deportiva o cotidiana del paciente. Es la etapa final de la rehabilitación, que integra fuerza, propiocepción, coordinación y resistencia en un contexto funcional real. El criterio de inicio es fuerza ≥ 70–80% del lado sano y EVA 0/10 en ejercicio de fuerza.',
      phases:[
        { phase:'Crónica tardía (sem 6–12)', pill:'pill-green', col:'kp-phase-green',
          detail:'Patrones funcionales específicos (sentadilla, salto, giro, empuje-tracción según actividad). Carga progresiva, velocidad progresiva. Fuerza ≥ 70–80% criterio de inicio.',
          params:['Fuerza ≥ 70–80% lado sano','EVA 0/10 en fuerza','Patrones específicos','Velocidad progresiva'] },
        { phase:'Retorno al deporte/trabajo', pill:'pill-green', col:'kp-phase-green',
          detail:'Marcha → trote → carrera → cambios dirección → deporte específico. Cada etapa mínimo 1–2 semanas sin síntomas. Alta con fuerza ≥ 90% lado sano.',
          params:['Alta: fuerza ≥ 90% lado sano','2 sem por etapa sin síntomas','Progresión por etapas','Test funcional previo al alta'] },
      ],
      ref:'<strong>Gokeler A et al.</strong> Br J Sports Med, 2017;51(18):1313–1318. DOI: 10.1136/bjsports-2016-096885 — El criterio de retorno basado en fuerza ≥ 90% reduce el riesgo de re-lesión al 9% vs 28% con criterios temporales. / <strong>Ardern CL et al.</strong> Br J Sports Med, 2016;50(19):1179–1184. DOI: 10.1136/bjsports-2016-096054 — El umbral mínimo funcional para actividades laborales de alta demanda es ≥ 85%.' },

    { title:'Bomba muscular y ejercicio en descarga',
      sub:'Actividad muscular sin carga axial articular',
      desc:'Ejercicio en medio acuático, bicicleta estática o contracciones rítmicas en descarga. Permite mantener la actividad metabólica muscular y cardiovascular sin carga compresiva sobre el cartílago o el tejido en reparación. La bomba muscular activa (especialmente la bomba sural en MMII) mejora el retorno venoso y linfático, reduciendo el edema activamente.',
      phases:[
        { phase:'Aguda–Subaguda (sem 1–4)', pill:'pill-red', col:'kp-phase-red',
          detail:'Contracciones isométricas rítmicas + movilización activa distal. Cada 1–2 h para bomba venosa. Bicicleta o piscina 20–30 min desde sem 1–2 si hay patología articular de carga.',
          params:['Isométrico rítmico cada 1–2 h','Bicicleta / piscina 20–30 min','3–4 veces/semana','Sin carga axial'] },
        { phase:'Crónica (mantenimiento)', pill:'pill-green', col:'kp-phase-green',
          detail:'Ejercicio aeróbico en descarga como actividad complementaria de mantenimiento. 30 min, 3–5 veces/semana.',
          params:['30 min aeróbico','3–5 veces/semana','Intensidad moderada (60–70% FCmáx)','Complementario al trabajo de fuerza'] },
      ],
      ref:'<strong>Fransen M et al.</strong> Cochrane Database Syst Rev, 2015;(1):CD004376. DOI: 10.1002/14651858.CD004376.pub3 — Meta-análisis 54 estudios: el ejercicio en descarga reduce el dolor en artrosis en 0.49 DE y mejora la función en 0.52 DE; la bicicleta muestra el mejor perfil beneficio-riesgo articular.' },
  ],
};

