/* ===== MECANISMOS DATA ===== */
const MECHS = [
  {num:'1',nc:'c-blue-n',name:'TENS — Teoría de la compuerta del dolor',
    body:'Las corrientes de <span class="mech-highlight">alta frecuencia (80–150 Hz)</span> activan fibras A-β (tacto y presión) de gran diámetro. Estas fibras excitan interneuronas inhibitorias en el asta posterior medular (sustancia gelatinosa de Rolando), que "cierran la compuerta" bloqueando la transmisión de señales dolorosas desde fibras C y A-δ hacia el cerebro. Las corrientes de <span class="mech-highlight">baja frecuencia (1–10 Hz)</span> generan potenciales de acción en fibras motoras Aα que estimulan la liberación de β-endorfinas, encefalinas y dinorfinas en el asta posterior y a nivel supraespinal, produciendo analgesia sistémica y duradera de 4–6 horas post-sesión.'},
  {num:'2',nc:'c-green-n',name:'Interferencial — Interferencia de frecuencias medias',
    body:'Se aplican dos corrientes de <span class="mech-highlight">~4000 Hz</span> (media frecuencia) con una pequeña diferencia entre sí (p. ej. 4000 Hz y 4080 Hz). La media frecuencia supera fácilmente la resistencia cutánea. Al cruzarse en el tejido profundo, se "interfieren" y generan una frecuencia modulada de amplitud (AMF) igual a la diferencia: <span class="mech-highlight">80 Hz</span> en este ejemplo. Esta AMF actúa como la frecuencia terapéutica real sobre nervios y músculo profundo, combinando Gate Control (alta AMF), liberación endorfínica (baja AMF) y efecto simpaticolítico vasodilatador (AMF 25–50 Hz).'},
  {num:'3',nc:'c-amber-n',name:'Ultrasonido — Efectos térmico y mecánico',
    body:'El transductor convierte energía eléctrica en vibraciones mecánicas a <span class="mech-highlight">1–3 MHz</span>. En <strong>modo continuo</strong>, la vibración molecular continua genera calor profundo por fricción (efecto térmico), aumentando la extensibilidad del colágeno, la velocidad de conducción nerviosa y la permeabilidad vascular. En <strong>modo pulsado</strong>, el calor es mínimo y predomina el efecto mecánico: <span class="mech-highlight">cavitación estable</span> (microburbujas oscilantes que generan microcorrientes de fluido) y streaming acústico, que estimulan directamente fibroblastos, macrófagos y células de Schwann sin elevar la temperatura.'},
  {num:'4',nc:'c-pink-n',name:'Laser 830 nm — Fotobiomodulación',
    body:'Los fotones a <span class="mech-highlight">830 nm</span> son absorbidos específicamente por el <span class="mech-highlight">citocromo c oxidasa</span> en el complejo IV de la cadena de transporte electrónico mitocondrial. Esto incrementa el potencial de membrana mitocondrial, acelera la producción de ATP y activa factores de transcripción redox-sensibles (NF-κB, AP-1). Los efectos resultantes incluyen: mayor síntesis de colágeno por fibroblastos, proliferación de tenocitos y condrocitos, inhibición de COX-2 y reducción de prostaglandinas, activación de VEGF para neovascularización, e inhibición de la conducción en fibras nociceptivas C y A-δ. El efecto es exclusivamente <span class="mech-highlight">fotoquímico, sin calor</span>. La ventana 820–850 nm es la de máxima absorción en citocromo c oxidasa.'},
  {num:'5',nc:'c-purple-n',name:'Corrientes rusas — Estimulación de media frecuencia',
    body:'La portadora de <span class="mech-highlight">2500 Hz</span> supera la impedancia cutánea sin producir dolor ni quemadura en la piel, permitiendo intensidades elevadas que generan contracciones musculares de mayor fuerza que el TENS convencional. Se modula en <span class="mech-highlight">ráfagas de 50 Hz</span> con ciclos ON/OFF configurables, lo que produce contracciones tetánicas controladas. Esto recluta preferentemente <span class="mech-highlight">fibras musculares tipo II</span> (rápidas), estimula la síntesis proteica miofibrilar e induce adaptaciones neuromusculares similares al ejercicio de fuerza, siendo especialmente eficaz en atrofia por desuso post-inmovilización.'},
  {num:'6',nc:'c-coral-n',name:'Magnetoterapia — Inducción de microcorrientes (Ley de Faraday)',
    body:'El campo magnético pulsado de baja frecuencia <span class="mech-highlight">penetra sin atenuación</span> a través de todos los tejidos, incluido el hueso cortical. Por ley de inducción electromagnética de Faraday, induce <span class="mech-highlight">microcorrientes eléctricas</span> en los tejidos conductores. Estas microcorrientes activan canales iónicos dependientes de voltaje (Na⁺, Ca²⁺, K⁺), estimulan la proliferación de osteoblastos y fibroblastos, mejoran la microcirculación local, reducen la síntesis de prostaglandinas e interleucinas proinflamatorias (IL-1β, TNF-α) y modulan la permeabilidad de la membrana celular. La frecuencia de <span class="mech-highlight">1–10 Hz</span> es la más osteogénica por resonar con la frecuencia natural de los osteoblastos.'},
  {num:'7',nc:'c-teal-n',name:'Ondas de choque radiales — Microtraumatismo controlado',
    body:'Las ondas de presión neumáticas generan <span class="mech-highlight">pulsos de alta presión (1.5–4 bar)</span> que se propagan radialmente en el tejido. El efecto mecánico directo fragmenta calcificaciones, rompe adherencias del tejido fibrótico y desorganiza la estructura anormal del tendón degenerativo. Secundariamente, el microtraumatismo controlado activa mastocitos y macrófagos que liberan factores de crecimiento: <span class="mech-highlight">VEGF</span> (neovascularización), <span class="mech-highlight">TGF-β1</span> (síntesis de colágeno), <span class="mech-highlight">IGF-1</span> (proliferación celular). Esto "reinicia" la cascada de reparación en tendones que habían entrado en un estado degenerativo sin capacidad regenerativa espontánea, siendo la indicación principal en tendinopatías refractarias de más de 3 meses.'},
];

