/* ===== TIEMPOS DATA ===== */
const TISSUES = [
  { id:'musculo', icon:'💪', name:'Músculo', color:'red',
    desc:'Tejido altamente vascularizado con capacidad regenerativa media. La recuperación depende de la extensión de la lesión (grado I, II o III) y de la actividad contráctil preservada.',
    totalTime:'3 semanas – 6 meses',
    timingPills:[{l:'Grado I: 1–3 sem',c:'green'},{l:'Grado II: 3–8 sem',c:'amber'},{l:'Grado III: 3–6 meses',c:'red'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 5 días', color:'red',
        body:'Rotura de fibras musculares y vasos sanguíneos → hematoma intramuscular. Activación del complemento y liberación de histamina, prostaglandinas (PGE2) y bradiquinina. Infiltración de neutrófilos (pico a las 6–12 h) que fagocitan debris celular. Transición a macrófagos M1 pro-inflamatorios (día 2–4) que orquestan el cambio hacia la fase reparativa. Signos clínicos: dolor intenso, calor, rubor, edema, impotencia funcional.',
        agents:[{l:'TENS convencional',c:'blue'},{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'},{l:'Magnetoterapia 10–25 Hz',c:'coral'}]},
      { name:'Fase proliferativa / reparativa', time:'5 días – 3–4 semanas', color:'amber',
        body:'Transición de macrófagos M1 → M2 anti-inflamatorios (día 2–4). Activación de células satélite (mioblastos) que proliferan, se fusionan y forman miotubos. Síntesis de colágeno tipo III (cicatriz provisional) por fibroblastos infiltrantes. Angiogénesis para revascularizar el tejido. El nuevo tejido muscular es funcionalmente débil y susceptible a re-lesión. Clínicamente: dolor en carga, pérdida de fuerza y flexibilidad.',
        agents:[{l:'US pulsado 1:1',c:'amber'},{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'Corrientes rusas (desde sem 2)',c:'purple'},{l:'Magnetoterapia',c:'coral'}]},
      { name:'Fase de remodelación', time:'3 semanas – 6 meses', color:'green',
        body:'Maduración y reorganización de la cicatriz fibrosa. El colágeno tipo III es reemplazado progresivamente por colágeno tipo I (más resistente), orientado según las líneas de tensión mecánica. Las fibras musculares regeneradas aumentan en diámetro (hipertrofia). La recuperación completa de la fuerza y propiedades viscoelásticas puede tardar hasta 6 meses en lesiones grado III. El tejido cicatrizal nunca recupera la arquitectura perfecta del músculo original.',
        agents:[{l:'Corrientes rusas',c:'purple'},{l:'US continuo',c:'amber'},{l:'TENS acupuntural',c:'blue'},{l:'Laser 830 nm 4–6 J',c:'pink'}]},
    ],
    note:'<strong>Factores que alargan la recuperación:</strong> re-lesión en fase proliferativa, inmovilización prolongada, déficit de proteínas, edad avanzada y mala vascularización local. El retorno al deporte antes de recuperar el 90% de fuerza del lado sano multiplica el riesgo de recidiva.'},

  { id:'tendon', icon:'🔗', name:'Tendón', color:'amber',
    desc:'Tejido hipovascularizado y con metabolismo lento. La recuperación es prolongada y el riesgo de degeneración crónica (tendinosis) es elevado si no se gestiona correctamente la carga mecánica.',
    totalTime:'6 semanas – 2 años',
    timingPills:[{l:'Inflamación: 0–2 sem',c:'red'},{l:'Proliferación: 2–10 sem',c:'amber'},{l:'Remodelación: 3m – 2 años',c:'green'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 2 semanas', color:'red',
        body:'Rotura parcial o total de fibras de colágeno y tenocitos. Hemorragia intratendinosa y activación de la cascada inflamatoria. Infiltración de neutrófilos y macrófagos que liberan metaloproteasas (MMP-1, MMP-3) para eliminar colágeno dañado. La hipovascularización del tendón ralentiza esta fase respecto al músculo. Síntesis de matriz provisional rica en fibronectina. Clínicamente: dolor en reposo y al movimiento, sensibilidad a la palpación, crepitación.',
        agents:[{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'},{l:'TENS convencional',c:'blue'},{l:'Magnetoterapia 10–25 Hz',c:'coral'}]},
      { name:'Fase proliferativa', time:'2 – 10 semanas', color:'amber',
        body:'Proliferación de tenocitos y síntesis masiva de colágeno tipo III (90% del colágeno neoformado). Las fibras son desorganizadas, con orientación aleatoria y menor resistencia mecánica que el tejido original. Vascularización provisional (hipervascularización detectable por ecografía Doppler). Aumento de proteoglicanos (agrecano, decorina) que retienen agua → engrosamiento fusiforme del tendón. Clínicamente: dolor selectivo en carga, inicio de recuperación funcional.',
        agents:[{l:'US continuo/pulsado',c:'amber'},{l:'Laser 830 nm 3–6 J',c:'pink'},{l:'Interferencial 80 Hz',c:'green'},{l:'Terapia combinada',c:'purple'}]},
      { name:'Fase de remodelación', time:'3 meses – 2 años', color:'green',
        body:'Reorganización del colágeno tipo III → colágeno tipo I según el eje de tensión mecánica. Este proceso depende directamente de la carga mecánica progresiva (mecanotransducción). La resistencia mecánica del tendón alcanza el 80% del original a los 6 meses y el 100% puede tardar hasta 1–2 años. Sin carga progresiva, el tendón queda como tejido fibrótico desorganizado (tendinosis). En tendinopatías crónicas (>3 meses), la neovascularización patológica y la apoptosis de tenocitos impiden la reparación espontánea.',
        agents:[{l:'Ondas de choque (crónico)',c:'teal'},{l:'Laser 830 nm 6–10 J',c:'pink'},{l:'US continuo',c:'amber'},{l:'Magnetoterapia',c:'coral'}]},
    ],
    note:'<strong>Carga excéntrica progresiva:</strong> es el estímulo mecánico más eficaz para la remodelación tendinosa. Debe iniciarse en fase proliferativa tardía (semana 4–6) de forma gradual. Las ondas de choque están indicadas exclusivamente en tendinopatías crónicas refractarias de más de 3 meses.'},

  { id:'ligamento', icon:'🔀', name:'Ligamento', color:'blue',
    desc:'Tejido conectivo denso con vascularización variable según su localización (intraarticular vs extraarticular). Los ligamentos intraarticulares (LCA) tienen muy baja capacidad de cicatrización espontánea.',
    totalTime:'6 semanas – 24 meses (LCA)',
    timingPills:[{l:'Esguince I–II: 3–12 sem',c:'amber'},{l:'Esguince III: 3–6 meses',c:'red'},{l:'LCA (qx): 9–24 meses',c:'blue'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 72 horas', color:'red',
        body:'Rotura de fibras colágenas y vasos ligamentosos → hematoma articular o periarticular. Liberación de citoquinas pro-inflamatorias (IL-1β, TNF-α) y factores de crecimiento (PDGF, TGF-β). Los fibroblastos ligamentosos periféricos comienzan a migrar hacia la zona lesionada. En ligamentos intraarticulares (LCA, LCP), el líquido sinovial inhibe la coagulación y la formación del coágulo de fibrina inicial, impidiendo la cicatrización espontánea. Clínicamente: hemartros, dolor agudo, inestabilidad articular.',
        agents:[{l:'TENS convencional',c:'blue'},{l:'Laser 830 nm 1–2 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'Interferencial 25–50 Hz',c:'green'}]},
      { name:'Fase proliferativa', time:'72 h – 6 semanas', color:'amber',
        body:'Síntesis de colágeno tipo III por fibroblastos activados. Formación de un "ligamento cicatrizal" rico en agua y proteoglicanos, con menor resistencia tensil. La neovascularización es esencial para nutrir los fibroblastos reparadores. En esguinces grado I y II, este proceso es suficiente para una recuperación funcional. En grado III (rotura completa), la brecha entre los extremos puede impedir la unión espontánea, especialmente en el LCA. Clínicamente: dolor con movimiento, inicio de estabilización dinámica por musculatura periarticular.',
        agents:[{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'Interferencial 80 Hz',c:'green'},{l:'Magnetoterapia',c:'coral'}]},
      { name:'Fase de remodelación', time:'6 semanas – 18 meses', color:'green',
        body:'Reorganización del colágeno tipo III → I. El ligamento cicatrizal extraarticular puede alcanzar el 70–80% de resistencia original al año. La propiocepción se recupera más lentamente que la resistencia mecánica (fibras nerviosas mecanorreceptoras en el ligamento deben regenerarse). En reconstrucción del LCA, el injerto pasa por un proceso de "ligamentización": necrosis inicial → revascularización (mes 3–4) → proliferación celular → remodelación (mes 9–18). El criterio de retorno al deporte es funcional, no temporal.',
        agents:[{l:'US continuo',c:'amber'},{l:'Corrientes rusas (músculo periart.)',c:'purple'},{l:'Laser 830 nm',c:'pink'},{l:'TENS acupuntural',c:'blue'}]},
    ],
    note:'<strong>Ligamento intraarticular vs extraarticular:</strong> el LLI de rodilla (extraarticular) cicatriza espontáneamente en grado III; el LCA (intraarticular) NO cicatriza sin reconstrucción quirúrgica. La rehabilitación post-LCA dura 9–12 meses mínimo para reducir el riesgo de re-rotura.'},

  { id:'hueso', icon:'🦴', name:'Hueso', color:'green',
    desc:'Tejido con la mayor capacidad regenerativa del organismo: cicatriza sin cicatriz (tejido idéntico al original). El proceso es complejo y altamente dependiente de la estabilidad mecánica y la vascularización.',
    totalTime:'6 – 24 semanas (fractura simple)',
    timingPills:[{l:'Consolidación clínica: 6–12 sem',c:'amber'},{l:'Consolidación ósea: 3–6 meses',c:'green'},{l:'Remodelación: hasta 2 años',c:'blue'}],
    phases:[
      { name:'Hematoma fracturario e inflamación', time:'0 – 1–2 semanas', color:'red',
        body:'La rotura ósea genera un hematoma fracturario rico en plaquetas que libera PDGF, TGF-β y BMP (proteínas morfogenéticas óseas). Este hematoma actúa como andamiaje provisional y como reservorio de factores de crecimiento. Neutrófilos y macrófagos fagocitan tejido necrótico. Las células mesenquimales periósticas y del endostio se activan. La hipoxia local estimula la angiogénesis. En fracturas con desplazamiento o mala vascularización, esta fase se prolonga.',
        agents:[{l:'Magnetoterapia 1–10 Hz',c:'coral'},{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'}]},
      { name:'Callo blando (fibrocartilaginoso)', time:'1 – 4 semanas', color:'amber',
        body:'Las células mesenquimales se diferencian en condrocitos y fibroblastos que forman un callo provisional de cartílago hialino y fibrocartílago (callo blando). Esta estructura une mecánicamente los fragmentos pero es frágil. Depende de la movilidad interfragmentaria: si es excesiva → predomina fibrocartílago; si es mínima → osificación intramembranosa directa. La vascularización del callo es crítica: isquemia → pseudoartrosis. Radiológicamente visible como nube de densidad aumentada.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'US pulsado (0.3 W/cm²)',c:'amber'},{l:'Laser 830 nm',c:'pink'}]},
      { name:'Callo duro (mineralización)', time:'4 – 12 semanas', color:'green',
        body:'Los condrocitos del callo blando sufren hipertrofia y apoptosis → calcificación de la matriz cartilaginosa. Invasión vascular y diferenciación de osteoblastos que depositan osteoide (colágeno tipo I + hidroxiapatita). El callo se mineraliza progresivamente (callo duro). La fractura deja de ser visible por imagen. La rigidez mecánica aumenta exponencialmente. El tejido es ya hueso primario (hueso trenzado, poco organizado). Clínicamente: resolución del dolor en carga.',
        agents:[{l:'Magnetoterapia 10–25 Hz',c:'coral'},{l:'US continuo (fase tardía)',c:'amber'},{l:'Laser 830 nm',c:'pink'}]},
      { name:'Remodelación ósea', time:'3 meses – 2 años', color:'blue',
        body:'Los osteoclastos reabsorben el hueso trenzado desordenado y los osteoblastos depositan hueso laminar orientado según las líneas de tensión de Wolff. La médula ósea se reconstituye. La cortical recupera su grosor y densidad. En adultos jóvenes, la remodelación puede restaurar completamente la morfología original sin huella radiológica de fractura. En fracturas mal reducidas o con mala vascularización → consolidación viciosa o pseudoartrosis.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Ondas de choque (pseudoartrosis)',c:'teal'},{l:'US continuo',c:'amber'}]},
    ],
    note:'<strong>Factores de riesgo para consolidación lenta:</strong> edad >50 años, tabaquismo (reduce vascularización en 30–40%), diabetes, osteoporosis, AINEs prolongados (inhiben prostaglandinas necesarias para la fase inflamatoria inicial), inmovilización excesiva o inestabilidad mecánica. La magnetoterapia 1–10 Hz es el agente físico con mayor evidencia en fracturas de lenta consolidación y pseudoartrosis.'},

  { id:'cartilago', icon:'🔵', name:'Cartílago articular', color:'teal',
    desc:'Tejido avascular, aneural y alinfático con capacidad de regeneración MUY LIMITADA. La calidad de la reparación depende críticamente de si la lesión alcanza el hueso subcondral vascularizado (lesión profunda) o no (lesión superficial). Los condrocitos tienen baja actividad metabólica y no pueden migrar hacia la zona lesionada.',
    totalTime:'Meses – 2 años (sin recuperación completa)',
    timingPills:[{l:'Superficial: sin reparación real',c:'red'},{l:'Profunda: fibrocartílago 2–12 m',c:'amber'},{l:'Remodelación: 1–2 años',c:'blue'},{l:'Microfracturas/ACI: 6–18 m',c:'teal'}],
    phases:[
      { name:'Fase aguda (superficial) / hemorrágica (profunda)', time:'0 – 72 h · Días 0–7', color:'red',
        body:'<strong>Lesión superficial (no alcanza hueso subcondral):</strong> NO se genera respuesta inflamatoria clásica por ausencia de vascularización. Los condrocitos adyacentes aumentan brevemente la síntesis de colágeno tipo II, pero la respuesta es insuficiente. Mediadores: IL-1β y TNF-α estimulan MMP-1 y MMP-13 (metaloproteasas degradativas del colágeno tipo II) sin contrapeso reparador efectivo. El defecto persiste y progresa hacia artrosis.<br><strong>Lesión profunda (alcanza hueso subcondral):</strong> hemorragia subarticular → coágulo de fibrina rico en plaquetas que libera PDGF y TGF-β iniciando la cascada reparadora. Células mesenquimales (MSC) del hueso subcondral comienzan a migrar al defecto. Fase hemorrágica: 24–72 h. Fase inflamatoria activa: días 3–7.',
        agents:[{l:'TENS convencional 80–150 Hz',c:'blue'},{l:'Magnetoterapia 10–50 Hz',c:'coral'},{l:'Laser 830 nm 1–2 J',c:'pink'}]},
      { name:'Fase proliferativa / formación de fibrocartílago', time:'Semanas 2–6 · Meses 2–12', color:'amber',
        body:'Las MSC del hueso subcondral se diferencian en condroblastos bajo la influencia de <strong>BMP-2 y BMP-7</strong> (proteínas morfogenéticas óseas) y TGF-β1. Se sintetiza colágeno tipo I (fibrocartílago) en lugar del colágeno tipo II del cartílago hialino original. El fibrocartílago es mecánicamente inferior: menor contenido de agrecano, mayor rigidez, peor respuesta a ciclos de carga repetida. Mediadores: VEGF (angiogénesis subcondral), FGF (proliferación celular), IGF-1 (diferenciación condrogénica). <em>Post-microfracturas:</em> las primeras 6–8 semanas son críticas — evitar carga mecánica intensa y US de alta intensidad sobre la zona.',
        agents:[{l:'US pulsado 1:4 · 0.5–1.5 W/cm²',c:'amber'},{l:'Laser 830 nm 2–5 J',c:'pink'},{l:'Magnetoterapia 10–25 Hz · 5–15 mT',c:'coral'},{l:'Interferencial 80 Hz',c:'green'}]},
      { name:'Maduración y remodelación del fibrocartílago', time:'3 meses – 2 años', color:'green',
        body:'El fibrocartílago neoformado madura progresivamente, pero nunca alcanza las propiedades biomecánicas del cartílago hialino: menor contenido de agrecano, menor resistencia a compresión repetida, mayor riesgo de fisuración tardía. IGF-1 y TGF-β guían la remodelación del colágeno tipo I. <strong>Descarga articular controlada:</strong> fundamental los primeros 3–6 meses para la integración del tejido. <em>Post-ACI/MACI:</em> el implante de condrocitos autólogos puede generar tejido más próximo al hialino; período crítico de 12 semanas para la fijación del implante → evitar US de alta intensidad y cargas de impacto.',
        agents:[{l:'US pulsado · baja intensidad',c:'amber'},{l:'Laser 830 nm 3–6 J',c:'pink'},{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Interferencial (analgesia)',c:'green'}]},
    ],
    note:'<strong>El cartílago articular NO se regenera espontáneamente.</strong> Lesión superficial → progresión hacia artrosis. Lesión profunda → fibrocartílago (inferior al hialino). Las microfracturas y el ACI/MACI buscan tejido reparativo con calidad variable. <strong>Condroprotección a largo plazo:</strong> magnetoterapia y laser 830 nm inhiben MMP-13 (degradativa del colágeno tipo II) y estimulan la síntesis de colágeno tipo II. <strong>Contraindicado en aguda sobre cartílago:</strong> US continuo de alta intensidad y cargas mecánicas en las primeras 6–8 semanas post-microfractura.'},

  { id:'menisco', icon:'🌙', name:'Menisco', color:'blue',
    desc:'Fibrocartílago semilunar con función de amortiguación, distribución de carga y estabilidad articular en la rodilla. La capacidad de cicatrización depende críticamente de la zona lesionada: zona roja-roja (periférica, bien vascularizada por la arteria genicular) vs zona blanca-blanca (avascular, nutrición solo por difusión del líquido sinovial).',
    totalTime:'6 semanas – 6 meses (zona vascularizada)',
    timingPills:[{l:'Zona roja-roja: sutura viable',c:'green'},{l:'Zona roja-blanca: variable',c:'amber'},{l:'Zona blanca-blanca: meniscectomía',c:'red'},{l:'Post-sutura: 3–6 meses',c:'blue'}],
    phases:[
      { name:'Fase hemorrágica e inflamatoria', time:'0 – 72 h · Días 3–14', color:'red',
        body:'<strong>Zona roja-roja:</strong> la rotura genera hematoma local rico en plaquetas → liberación de PDGF y TGF-β que inician la cascada reparativa. Respuesta inflamatoria completa con neutrófilos (0–72 h) y macrófagos (día 2–4). Liberación de IL-1, TNF-α y TGF-β. La red vascular de la arteria genicular (rama de la arteria poplítea) irriga el tercio periférico meniscal.<br><strong>Zona blanca-blanca:</strong> sin vascularización, la nutrición ocurre únicamente por difusión desde el líquido sinovial. Respuesta inflamatoria mínima o ausente → cicatrización espontánea no posible. Clínicamente: dolor articular medial o lateral, bloqueo articular, signo de McMurray positivo.',
        agents:[{l:'TENS convencional 80–150 Hz',c:'blue'},{l:'Magnetoterapia baja intensidad',c:'coral'},{l:'Laser 830 nm 1–2 J',c:'pink'}]},
      { name:'Fase proliferativa', time:'Semanas 1 – 6', color:'amber',
        body:'Fibroblastos y condroblastos migran desde la zona periférica vascularizada hacia el defecto. Síntesis de colágeno tipo I (fibrocartílago de reparación) y proteoglicanos. Mediadores: TGF-β y FGF (proliferación fibroblástica), PDGF (quimiotaxis celular). La cicatrización fibrovascular rellena el defecto en la zona roja; en la zona roja-blanca la respuesta es menos predecible. <em>Post-sutura meniscal:</em> las primeras 6 semanas son el período crítico → descarga parcial o total (4–6 sem según técnica quirúrgica) para proteger la sutura. Evitar US de alta intensidad directamente sobre la sutura.',
        agents:[{l:'US pulsado 1 MHz · 0.5–1 W/cm² · 50%',c:'amber'},{l:'Laser 830 nm 2–4 J',c:'pink'},{l:'Interferencial AMF 80–120 Hz',c:'green'},{l:'Magnetoterapia',c:'coral'}]},
      { name:'Fase de remodelación', time:'Meses 2 – 6+', color:'green',
        body:'Reorganización y maduración del tejido fibrocartilaginoso. TGF-β e IGF-1 guían la orientación de las fibras de colágeno tipo I según las líneas de carga. El tejido reparado nunca recupera las propiedades biomecánicas del menisco original (menor contenido de colágeno tipo II y condroitín sulfato). La resistencia mecánica alcanza el 60–70% del original a los 6 meses. <em>Post-meniscectomía parcial:</em> sin objetivo de reparación tisular; énfasis en recuperación funcional y protección del cartílago articular subyacente — mayor riesgo de artrosis a largo plazo.',
        agents:[{l:'US pulsado · organización colágeno',c:'amber'},{l:'Magnetoterapia 10–25 Hz',c:'coral'},{l:'Interferencial (analgesia profunda)',c:'green'},{l:'Laser 830 nm (condroprotección)',c:'pink'}]},
    ],
    note:'<strong>Zonas meniscales:</strong> <em>Roja-roja</em> (tercio periférico, vascularizada) → sutura con buen pronóstico; <em>Roja-blanca</em> (tercio medio, parcialmente vascularizada) → sutura con pronóstico variable; <em>Blanca-blanca</em> (tercio interno, avascular) → generalmente meniscectomía parcial. <strong>Consecuencia de meniscectomía:</strong> pérdida del 50–70% del menisco → aumento de presión sobre cartílago articular del 40–50% → riesgo elevado de gonartrosis a 10–20 años. <strong>Magnetoterapia y laser 830 nm</strong> tienen rol en la condroprotección del cartílago residual post-meniscectomía inhibiendo MMP-13.'},

  { id:'nervio', icon:'⚡', name:'Nervio periférico', color:'purple',
    desc:'Tejido con capacidad regenerativa limitada y lenta. La recuperación depende del tipo de lesión (neuroapraxia, axonotmesis, neurotmesis) y de la distancia que debe recorrer el axón regenerante hasta el órgano efector.',
    totalTime:'Semanas – 2 años (según tipo y distancia)',
    timingPills:[{l:'Neuroapraxia: 2–12 sem',c:'green'},{l:'Axonotmesis: 1–18 meses',c:'amber'},{l:'Neurotmesis: meses–años / permanente',c:'red'}],
    phases:[
      { name:'Degeneración Walleriana', time:'0 – 3 semanas', color:'red',
        body:'Distal a la lesión: el axón y la vaina de mielina se desintegran (degeneración walleriana). Las células de Schwann fagocitan los detritos y forman "bandas de Büngner" (tubos de guía) que orientarán la regeneración. Los macrófagos infiltran el nervio y eliminan restos de mielina. Proximal a la lesión: el soma neuronal sufre cromatolisis central (aumento de síntesis proteica para la regeneración). La velocidad de conducción nerviosa distal desaparece. Clínicamente: déficit motor y/o sensitivo completo distal a la lesión.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Laser 830 nm 2–4 J',c:'pink'},{l:'TENS convencional (analgesia)',c:'blue'}]},
      { name:'Regeneración axonal', time:'3 semanas – meses/años', color:'amber',
        body:'El axón regenera desde el extremo proximal a una velocidad de aproximadamente 1–4 mm/día (1 mm/día como referencia clínica práctica). Los tubos de Büngner guían el crecimiento. Las células de Schwann re-mielinizan los axones regenerantes. La velocidad de regeneración disminuye con la distancia y la edad. Calculando la distancia lesión → órgano efector, se puede estimar el tiempo mínimo de recuperación funcional (p. ej.: lesión mediohumeral del nervio radial → 30 cm hasta extensores de muñeca → ~10 meses mínimo). Clínicamente: avance del signo de Tinel.',
        agents:[{l:'Laser 830 nm 3–6 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'Corrientes rusas (músculo denervado)',c:'purple'},{l:'US pulsado 1:4',c:'amber'}]},
      { name:'Reinervación y maduración', time:'Meses – 2 años', color:'green',
        body:'Los axones alcanzan los órganos efectores (placas motoras, corpúsculos sensoriales) y establecen nuevas sinapsis. La reinervación muscular previene la atrofia irreversible (fibrosis muscular por denervación prolongada >12–18 meses). La calidad de la recuperación sensitiva depende del número de axones que lleguen al órgano correcto (reinervación aberrante → disestesias). La mielina progresivamente aumenta su grosor y la velocidad de conducción se normaliza parcialmente. La recuperación completa raramente alcanza el 100% en neurotmesis.',
        agents:[{l:'Corrientes rusas / EMS',c:'purple'},{l:'Laser 830 nm',c:'pink'},{l:'TENS acupuntural',c:'blue'},{l:'Interferencial 1–10 Hz',c:'green'}]},
    ],
    note:'<strong>Regla clínica de los 1 mm/día:</strong> para estimar el tiempo mínimo de recuperación, mide la distancia en milímetros desde el sitio de lesión hasta el músculo más distal afectado y divide entre 1 mm/día. Suma 3–4 semanas de latencia para la degeneración walleriana. Las corrientes rusas y EMS son clave para mantener el trofismo muscular y prevenir la fibrosis durante la espera de reinervación.'},

  { id:'piel', icon:'🩹', name:'Piel / Tejido blando', color:'pink',
    desc:'Tejido con excelente vascularización y alta capacidad regenerativa. La epidermis se regenera completamente; la dermis cicatriza con tejido fibroso (colágeno tipo III → I). La profundidad y extensión determinan la calidad del resultado final.',
    totalTime:'2 semanas – 2 años (cicatriz madura)',
    timingPills:[{l:'Hemostasia: 0–6 h',c:'red'},{l:'Inflamación: 1–4 días',c:'amber'},{l:'Proliferación: 4–21 días',c:'green'},{l:'Remodelación: 3 sem–2 años',c:'blue'}],
    phases:[
      { name:'Hemostasia e inflamación', time:'0 – 4 días', color:'red',
        body:'Hemostasia: vasoconstricción inmediata → activación plaquetaria → coágulo de fibrina (tapón provisional). Las plaquetas liberan PDGF, TGF-β1 y EGF que inician la cascada de reparación. Inflamación: vasodilatación, extravasación de leucocitos. Neutrófilos (0–48 h) limpian el sitio. Macrófagos (48 h en adelante) orquestan la reparación liberando FGF, VEGF y TGF-β. La zona está eritematosa, caliente, edematosa y dolorosa. Una inflamación excesiva o prolongada conduce a cicatriz hipertrófica o queloide.',
        agents:[{l:'Laser 830 nm 1–2 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'US pulsado 1:4 (piel íntegra)',c:'amber'}]},
      { name:'Fase proliferativa', time:'4 días – 3 semanas', color:'amber',
        body:'Cuatro procesos simultáneos: (1) Re-epitelización: queratinocitos migran desde los márgenes de la herida a 0.5 mm/día. (2) Angiogénesis: brotes capilares (VEGF-dependiente) → tejido de granulación rosado y vascularizado. (3) Fibroplasia: fibroblastos sintetizan colágeno tipo III, fibronectina y ácido hialurónico formando la matriz provisional. (4) Contracción: miofibroblastos contraen los bordes de la herida reduciendo su superficie. La resistencia tensil alcanza el 20% del normal al final de esta fase.',
        agents:[{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'US pulsado 1:1',c:'amber'},{l:'Magnetoterapia',c:'coral'},{l:'Terapia combinada',c:'purple'}]},
      { name:'Remodelación de la cicatriz', time:'3 semanas – 2 años', color:'green',
        body:'El colágeno tipo III es sustituido por colágeno tipo I más grueso y organizado en haces paralelos (menor elasticidad que la piel normal). La vascularización excesiva regresa → cicatriz pálida. Los miofibroblastos sufren apoptosis. La resistencia tensil aumenta al 70–80% del normal a los 3 meses y al 80–85% máximo (nunca recupera el 100%). Una cicatriz patológica (hipertrófica o queloide) indica exceso de TGF-β1 con inhibición insuficiente de la síntesis de colágeno. El masaje, la silicona y la presión son tratamientos de primera línea para cicatrices patológicas.',
        agents:[{l:'US continuo (sobre cicatriz)',c:'amber'},{l:'Laser 830 nm',c:'pink'},{l:'Interferencial (fibrosis)',c:'green'}]},
    ],
    note:'<strong>Cicatriz hipertrófica vs queloide:</strong> la hipertrófica respeta los límites de la herida y puede regresar; el queloide invade tejido sano y raramente regresa espontáneamente. El laser 830 nm en dosis bajas (1–3 J/cm²) tiene evidencia en reducción de cicatrices hipertróficas al modular TGF-β1 y la actividad de miofibroblastos.'},
];
