/* ===== TIEMPOS DATA ===== */
const TISSUES = [
  { id:'musculo', icon:'💪', name:'Músculo', color:'red',
    desc:'Tejido altamente vascularizado con capacidad regenerativa media. La recuperación depende de la extensión de la lesión (grado I, II o III) y de la actividad contráctil preservada.',
    totalTime:'3 semanas – 6 meses',
    timingPills:[{l:'Grado I: 1–3 sem',c:'green'},{l:'Grado II: 3–8 sem',c:'amber'},{l:'Grado III: 3–6 meses',c:'red'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 72 horas', color:'red',
        body:'Rotura de fibras musculares y vasos sanguíneos → hematoma intramuscular. Activación del complemento y liberación de histamina, prostaglandinas (PGE2) y bradiquinina. Infiltración de neutrófilos (pico a las 6–12 h) que fagocitan debris celular. Aparición de macrófagos M1 pro-inflamatorios al final de la fase. Signos clínicos: dolor intenso, calor, rubor, edema, impotencia funcional.',
        agents:[{l:'TENS convencional',c:'blue'},{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'},{l:'Magnetoterapia 10–25 Hz',c:'coral'}]},
      { name:'Fase proliferativa / reparativa', time:'72 h – 3–4 semanas', color:'amber',
        body:'Transición de macrófagos M1 → M2 anti-inflamatorios (día 2–4). Activación de células satélite (mioblastos) que proliferan, se fusionan y forman miotubos. Síntesis de colágeno tipo III (cicatriz provisional) por fibroblastos infiltrantes. Angiogénesis para revascularizar el tejido. El nuevo tejido muscular es funcionalmente débil y susceptible a re-lesión. Clínicamente: dolor en carga, pérdida de fuerza y flexibilidad.',
        agents:[{l:'US pulsado 1:1',c:'amber'},{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'Corrientes rusas (desde sem 2)',c:'purple'},{l:'Magnetoterapia',c:'coral'}]},
      { name:'Fase de remodelación', time:'3 semanas – 6 meses', color:'green',
        body:'Maduración y reorganización de la cicatriz fibrosa. El colágeno tipo III es reemplazado progresivamente por colágeno tipo I (más resistente), orientado según las líneas de tensión mecánica. Las fibras musculares regeneradas aumentan en diámetro (hipertrofia). La recuperación completa de la fuerza y propiedades viscoelásticas puede tardar hasta 6 meses en lesiones grado III. El tejido cicatrizal nunca recupera la arquitectura perfecta del músculo original.',
        agents:[{l:'Corrientes rusas',c:'purple'},{l:'US continuo',c:'amber'},{l:'TENS acupuntural',c:'blue'},{l:'Laser 830 nm 4–6 J',c:'pink'}]},
    ],
    note:'<strong>Factores que alargan la recuperación:</strong> re-lesión en fase proliferativa, inmovilización prolongada, déficit de proteínas, edad avanzada y mala vascularización local. El retorno al deporte antes de recuperar el 90% de fuerza del lado sano multiplica el riesgo de recidiva.'},

  { id:'tendon', icon:'🔗', name:'Tendón', color:'amber',
    desc:'Tejido hipovascularizado y con metabolismo lento. La recuperación es prolongada y el riesgo de degeneración crónica (tendinosis) es elevado si no se gestiona correctamente la carga mecánica.',
    totalTime:'6 semanas – 12 meses',
    timingPills:[{l:'Inflamación: 0–2 sem',c:'red'},{l:'Proliferación: 2–10 sem',c:'amber'},{l:'Remodelación: 3–12 meses',c:'green'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 2 semanas', color:'red',
        body:'Rotura parcial o total de fibras de colágeno y tenocitos. Hemorragia intratendinosa y activación de la cascada inflamatoria. Infiltración de neutrófilos y macrófagos que liberan metaloproteasas (MMP-1, MMP-3) para eliminar colágeno dañado. La hipovascularización del tendón ralentiza esta fase respecto al músculo. Síntesis de matriz provisional rica en fibronectina. Clínicamente: dolor en reposo y al movimiento, sensibilidad a la palpación, crepitación.',
        agents:[{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'},{l:'TENS convencional',c:'blue'},{l:'Magnetoterapia 10–25 Hz',c:'coral'}]},
      { name:'Fase proliferativa', time:'2 – 10 semanas', color:'amber',
        body:'Proliferación de tenocitos y síntesis masiva de colágeno tipo III (90% del colágeno neoformado). Las fibras son desorganizadas, con orientación aleatoria y menor resistencia mecánica que el tejido original. Vascularización provisional (hipervascularización detectable por ecografía Doppler). Aumento de proteoglicanos (agrecano, decorina) que retienen agua → engrosamiento fusiforme del tendón. Clínicamente: dolor selectivo en carga, inicio de recuperación funcional.',
        agents:[{l:'US continuo/pulsado',c:'amber'},{l:'Laser 830 nm 3–6 J',c:'pink'},{l:'Interferencial 80 Hz',c:'green'},{l:'Terapia combinada',c:'purple'}]},
      { name:'Fase de remodelación', time:'3 meses – 12 meses', color:'green',
        body:'Reorganización del colágeno tipo III → colágeno tipo I según el eje de tensión mecánica. Este proceso depende directamente de la carga mecánica progresiva (mecanotransducción). La resistencia mecánica del tendón alcanza el 80% del original a los 6 meses y el 100% puede tardar hasta 1 año. Sin carga progresiva, el tendón queda como tejido fibrótico desorganizado (tendinosis). En tendinopatías crónicas (>3 meses), la neovascularización patológica y la apoptosis de tenocitos impiden la reparación espontánea.',
        agents:[{l:'Ondas de choque (crónico)',c:'teal'},{l:'Laser 830 nm 6–10 J',c:'pink'},{l:'US continuo',c:'amber'},{l:'Magnetoterapia',c:'coral'}]},
    ],
    note:'<strong>Carga excéntrica progresiva:</strong> es el estímulo mecánico más eficaz para la remodelación tendinosa. Debe iniciarse en fase proliferativa tardía (semana 4–6) de forma gradual. Las ondas de choque están indicadas exclusivamente en tendinopatías crónicas refractarias de más de 3 meses.'},

  { id:'ligamento', icon:'🔀', name:'Ligamento', color:'blue',
    desc:'Tejido conectivo denso con vascularización variable según su localización (intraarticular vs extraarticular). Los ligamentos intraarticulares (LCA) tienen muy baja capacidad de cicatrización espontánea.',
    totalTime:'6 semanas – 24 meses (LCA)',
    timingPills:[{l:'Esguince I–II: 3–12 sem',c:'amber'},{l:'Esguince III: 3–6 meses',c:'red'},{l:'LCA (qx): 9–24 meses',c:'blue'}],
    phases:[
      { name:'Fase inflamatoria', time:'0 – 72 horas', color:'red',
        body:'Rotura de fibras colágenas y vasos ligamentosos → hematoma articular o periarticular. Liberación de citoquinas pro-inflamatorias (IL-1β, TNF-α) y factores de crecimiento (PDGF, TGF-β). Los fibroblastos ligamentosos periféricos comienzan a migrar hacia la zona lesionada. En ligamentos intraarticulares (LCA, LCP), el líquido sinovial inhibe la coagulación y la formación del coágulo de fibrina inicial, impidiendo la cicatrización espontánea. Clínicamente: hemartros, dolor agudo, inestabilidad articular.',
        agents:[{l:'TENS convencional',c:'blue'},{l:'Laser 830 nm 1–2 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'Interferencial 25–50 Hz',c:'green'}]},
      { name:'Fase proliferativa', time:'72 h – 6 semanas', color:'amber',
        body:'Síntesis de colágeno tipo III por fibroblastos activados. Formación de un "ligamento cicatrizal" rico en agua y proteoglicanos, con menor resistencia tensil. La neovascularización es esencial para nutrir los fibroblastos reparadores. En esguinces grado I y II, este proceso es suficiente para una recuperación funcional. En grado III (rotura completa), la brecha entre los extremos puede impedir la unión espontánea, especialmente en el LCA. Clínicamente: dolor con movimiento, inicio de estabilización dinámica por musculatura periarticular.',
        agents:[{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'Interferencial 80 Hz',c:'green'},{l:'Magnetoterapia',c:'coral'}]},
      { name:'Fase de remodelación', time:'6 semanas – 12 meses', color:'green',
        body:'Reorganización del colágeno tipo III → I. El ligamento cicatrizal extraarticular puede alcanzar el 70–80% de resistencia original al año. La propiocepción se recupera más lentamente que la resistencia mecánica (fibras nerviosas mecanorreceptoras en el ligamento deben regenerarse). En reconstrucción del LCA, el injerto pasa por un proceso de "ligamentización": necrosis inicial → revascularización (mes 3–4) → proliferación celular → remodelación (mes 9–18). El criterio de retorno al deporte es funcional, no temporal.',
        agents:[{l:'US continuo',c:'amber'},{l:'Corrientes rusas (músculo periart.)',c:'purple'},{l:'Laser 830 nm',c:'pink'},{l:'TENS acupuntural',c:'blue'}]},
    ],
    note:'<strong>Ligamento intraarticular vs extraarticular:</strong> el LLI de rodilla (extraarticular) cicatriza espontáneamente en grado III; el LCA (intraarticular) NO cicatriza sin reconstrucción quirúrgica. La rehabilitación post-LCA dura 9–12 meses mínimo para reducir el riesgo de re-rotura.'},

  { id:'hueso', icon:'🦴', name:'Hueso', color:'green',
    desc:'Tejido con la mayor capacidad regenerativa del organismo: cicatriza sin cicatriz (tejido idéntico al original). El proceso es complejo y altamente dependiente de la estabilidad mecánica y la vascularización.',
    totalTime:'6 – 24 semanas (fractura simple)',
    timingPills:[{l:'Consolidación clínica: 6–12 sem',c:'amber'},{l:'Consolidación ósea: 3–6 meses',c:'green'},{l:'Remodelación: hasta 2 años',c:'blue'}],
    phases:[
      { name:'Hematoma fracturario e inflamación', time:'0 – 2 semanas', color:'red',
        body:'La rotura ósea genera un hematoma fracturario rico en plaquetas que libera PDGF, TGF-β y BMP (proteínas morfogenéticas óseas). Este hematoma actúa como andamiaje provisional y como reservorio de factores de crecimiento. Neutrófilos y macrófagos fagocitan tejido necrótico. Las células mesenquimales periósticas y del endostio se activan. La hipoxia local estimula la angiogénesis. En fracturas con desplazamiento o mala vascularización, esta fase se prolonga.',
        agents:[{l:'Magnetoterapia 1–10 Hz',c:'coral'},{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm 1–3 J',c:'pink'}]},
      { name:'Callo blando (fibrocartilaginoso)', time:'2 – 6 semanas', color:'amber',
        body:'Las células mesenquimales se diferencian en condrocitos y fibroblastos que forman un callo provisional de cartílago hialino y fibrocartílago (callo blando). Esta estructura une mecánicamente los fragmentos pero es frágil. Depende de la movilidad interfragmentaria: si es excesiva → predomina fibrocartílago; si es mínima → osificación intramembranosa directa. La vascularización del callo es crítica: isquemia → pseudoartrosis. Radiológicamente visible como nube de densidad aumentada.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'US pulsado (0.3 W/cm²)',c:'amber'},{l:'Laser 830 nm',c:'pink'}]},
      { name:'Callo duro (mineralización)', time:'4 – 12 semanas', color:'green',
        body:'Los condrocitos del callo blando sufren hipertrofia y apoptosis → calcificación de la matriz cartilaginosa. Invasión vascular y diferenciación de osteoblastos que depositan osteoide (colágeno tipo I + hidroxiapatita). El callo se mineraliza progresivamente (callo duro). La fractura deja de ser visible por imagen. La rigidez mecánica aumenta exponencialmente. El tejido es ya hueso primario (hueso trenzado, poco organizado). Clínicamente: resolución del dolor en carga.',
        agents:[{l:'Magnetoterapia 10–25 Hz',c:'coral'},{l:'US continuo (fase tardía)',c:'amber'},{l:'Laser 830 nm',c:'pink'}]},
      { name:'Remodelación ósea', time:'3 meses – 2 años', color:'blue',
        body:'Los osteoclastos reabsorben el hueso trenzado desordenado y los osteoblastos depositan hueso laminar orientado según las líneas de tensión de Wolff. La médula ósea se reconstituye. La cortical recupera su grosor y densidad. En adultos jóvenes, la remodelación puede restaurar completamente la morfología original sin huella radiológica de fractura. En fracturas mal reducidas o con mala vascularización → consolidación viciosa o pseudoartrosis.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Ondas de choque (pseudoartrosis)',c:'teal'},{l:'US continuo',c:'amber'}]},
    ],
    note:'<strong>Factores de riesgo para consolidación lenta:</strong> edad >50 años, tabaquismo (reduce vascularización en 30–40%), diabetes, osteoporosis, AINEs prolongados (inhiben prostaglandinas necesarias para la fase inflamatoria inicial), inmovilización excesiva o inestabilidad mecánica. La magnetoterapia 1–10 Hz es el agente físico con mayor evidencia en fracturas de lenta consolidación y pseudoartrosis.'},

  { id:'cartilago', icon:'🔵', name:'Cartílago articular', color:'teal',
    desc:'Tejido avascular y aneural con capacidad de regeneración MUY LIMITADA. Los condrocitos tienen baja actividad metabólica y no pueden migrar hacia la zona lesionada. Las lesiones profundas (grado III–IV Outerbridge) raramente sanan espontáneamente.',
    totalTime:'Meses – sin recuperación espontánea completa',
    timingPills:[{l:'Lesión superficial: regeneración nula',c:'red'},{l:'Lesión profunda (hueso subcondral): fibrocartílago',c:'amber'},{l:'Remodelación: 1–2 años',c:'blue'}],
    phases:[
      { name:'Respuesta inicial (lesión superficial)', time:'0 – semanas', color:'red',
        body:'Las lesiones que no alcanzan el hueso subcondral (grado I–II) NO generan respuesta inflamatoria clásica porque el cartílago es avascular. Los condrocitos locales aumentan brevemente su síntesis de colágeno tipo II y proteoglicanos, pero la zona de necrosis central no se rellena. Clínicamente asintomáticas inicialmente → fisuración progresiva → artrosis precoz si no se trata. El cartílago articular es como una esponja que se nutre únicamente por difusión del líquido sinovial.',
        agents:[{l:'US pulsado 1:4',c:'amber'},{l:'Magnetoterapia 10–25 Hz',c:'coral'},{l:'Laser 830 nm 3–5 J',c:'pink'}]},
      { name:'Respuesta reparativa (lesión osteocondral)', time:'Semanas – 3 meses', color:'amber',
        body:'Si la lesión alcanza el hueso subcondral vascularizado, se forma un coágulo de fibrina que actúa como andamiaje. Las células mesenquimales de la médula ósea migran y se diferencian en condroblastos (procedimiento Pridie / microfractura). Se forma fibrocartílago (colágeno tipo I predominante), que es mecánicamente inferior al cartílago hialino original (colágeno tipo II). El fibrocartílago tiene menor resistencia a la compresión y se desgasta más rápidamente con el tiempo.',
        agents:[{l:'Magnetoterapia 10–25 Hz',c:'coral'},{l:'US pulsado 1:4',c:'amber'},{l:'Laser 830 nm',c:'pink'},{l:'Interferencial 80 Hz',c:'green'}]},
      { name:'Maduración del fibrocartílago', time:'3 meses – 1–2 años', color:'green',
        body:'El fibrocartílago neoformado madura progresivamente y puede cubrir el defecto. Sin embargo, nunca alcanza las propiedades biomecánicas del cartílago hialino: menor contenido de agrecano, menor resistencia a ciclos repetidos de carga, mayor riesgo de fisuración tardía. Las estrategias actuales (implante de condrocitos autólogos, aloinjertos osteocondrales) intentan obtener tejido más próximo al hialino original. La descarga articular durante la fase de maduración es fundamental para su integración.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Laser 830 nm',c:'pink'},{l:'US pulsado',c:'amber'},{l:'Interferencial',c:'green'}]},
    ],
    note:'<strong>El cartílago articular NO se regenera espontáneamente.</strong> El manejo clínico busca enlentecer la progresión hacia artrosis y manejar los síntomas. La magnetoterapia y el laser 830 nm tienen evidencia de condroprotección al inhibir metaloproteasas (MMP-13) degradativas y estimular la síntesis de colágeno tipo II.'},

  { id:'nervio', icon:'⚡', name:'Nervio periférico', color:'purple',
    desc:'Tejido con capacidad regenerativa limitada y lenta. La recuperación depende del tipo de lesión (neuroapraxia, axonotmesis, neurotmesis) y de la distancia que debe recorrer el axón regenerante hasta el órgano efector.',
    totalTime:'Semanas – 2 años (según tipo y distancia)',
    timingPills:[{l:'Neuroapraxia: 2–12 sem',c:'green'},{l:'Axonotmesis: 1–18 meses',c:'amber'},{l:'Neurotmesis: meses–años / permanente',c:'red'}],
    phases:[
      { name:'Degeneración Walleriana', time:'0 – 3 semanas', color:'red',
        body:'Distal a la lesión: el axón y la vaina de mielina se desintegran (degeneración walleriana). Las células de Schwann fagocitan los detritos y forman "bandas de Büngner" (tubos de guía) que orientarán la regeneración. Los macrófagos infiltran el nervio y eliminan restos de mielina. Proximal a la lesión: el soma neuronal sufre cromatolisis central (aumento de síntesis proteica para la regeneración). La velocidad de conducción nerviosa distal desaparece. Clínicamente: déficit motor y/o sensitivo completo distal a la lesión.',
        agents:[{l:'Magnetoterapia 1–25 Hz',c:'coral'},{l:'Laser 830 nm 2–4 J',c:'pink'},{l:'TENS convencional (analgesia)',c:'blue'}]},
      { name:'Regeneración axonal', time:'3 semanas – meses/años', color:'amber',
        body:'El axón regenera desde el extremo proximal a una velocidad de aproximadamente 1–4 mm/día (1 mm/día como referencia clínica práctica). Los tubos de Büngner guían el crecimiento. Las células de Schwann re-mielinizan los axones regenerantes. La velocidad de regeneración disminuye con la distancia y la edad. Calculando la distancia lesión → órgano efector, se puede estimar el tiempo mínimo de recuperación funcional (p. ej.: lesión mediohumeral del nervio radial → 30 cm hasta extensores de muñeca → ~10 meses mínimo). Clínicamente: avance del signo de Tinel.',
        agents:[{l:'Laser 830 nm 3–6 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'Corrientes rusas (músculo denervado)',c:'purple'},{l:'US pulsado 1:4',c:'amber'}]},
      { name:'Reinervación y maduración', time:'Meses – 2 años', color:'green',
        body:'Los axones alcanzan los órganos efectores (placas motoras, corpúsculos sensoriales) y establecen nuevas sinapsis. La reinervación muscular previene la atrofia irreversible (fibrosis muscular por denervación prolongada >12–18 meses). La calidad de la recuperación sensitiva depende del número de axones que lleguen al órgano correcto (reinervación aberrante → disestesias). La mielina progresivamente aumenta su grosor y la velocidad de conducción se normaliza parcialmente. La recuperación completa raramente alcanza el 100% en neurotmesis.',
        agents:[{l:'Corrientes rusas / EMS',c:'purple'},{l:'Laser 830 nm',c:'pink'},{l:'TENS acupuntural',c:'blue'},{l:'Interferencial 1–10 Hz',c:'green'}]},
    ],
    note:'<strong>Regla clínica de los 1 mm/día:</strong> para estimar el tiempo mínimo de recuperación, mide la distancia en milímetros desde el sitio de lesión hasta el músculo más distal afectado y divide entre 1 mm/día. Suma 3–4 semanas de latencia para la degeneración walleriana. Las corrientes rusas y EMS son clave para mantener el trofismo muscular y prevenir la fibrosis durante la espera de reinervación.'},

  { id:'piel', icon:'🩹', name:'Piel / Tejido blando', color:'pink',
    desc:'Tejido con excelente vascularización y alta capacidad regenerativa. La epidermis se regenera completamente; la dermis cicatriza con tejido fibroso (colágeno tipo III → I). La profundidad y extensión determinan la calidad del resultado final.',
    totalTime:'2 semanas – 2 años (cicatriz madura)',
    timingPills:[{l:'Hemostasia: 0–6 h',c:'red'},{l:'Inflamación: 1–4 días',c:'amber'},{l:'Proliferación: 4–21 días',c:'green'},{l:'Remodelación: 3 sem–2 años',c:'blue'}],
    phases:[
      { name:'Hemostasia e inflamación', time:'0 – 4 días', color:'red',
        body:'Hemostasia: vasoconstricción inmediata → activación plaquetaria → coágulo de fibrina (tapón provisional). Las plaquetas liberan PDGF, TGF-β1 y EGF que inician la cascada de reparación. Inflamación: vasodilatación, extravasación de leucocitos. Neutrófilos (0–48 h) limpian el sitio. Macrófagos (48 h en adelante) orquestan la reparación liberando FGF, VEGF y TGF-β. La zona está eritematosa, caliente, edematosa y dolorosa. Una inflamación excesiva o prolongada conduce a cicatriz hipertrófica o queloide.',
        agents:[{l:'Laser 830 nm 1–2 J',c:'pink'},{l:'Magnetoterapia',c:'coral'},{l:'US pulsado 1:4 (piel íntegra)',c:'amber'}]},
      { name:'Fase proliferativa', time:'4 días – 3 semanas', color:'amber',
        body:'Cuatro procesos simultáneos: (1) Re-epitelización: queratinocitos migran desde los márgenes de la herida a 0.5 mm/día. (2) Angiogénesis: brotes capilares (VEGF-dependiente) → tejido de granulación rosado y vascularizado. (3) Fibroplasia: fibroblastos sintetizan colágeno tipo III, fibronectina y ácido hialurónico formando la matriz provisional. (4) Contracción: miofibroblastos contraen los bordes de la herida reduciendo su superficie. La resistencia tensil alcanza el 20% del normal al final de esta fase.',
        agents:[{l:'Laser 830 nm 3–5 J',c:'pink'},{l:'US pulsado 1:1',c:'amber'},{l:'Magnetoterapia',c:'coral'},{l:'Terapia combinada',c:'purple'}]},
      { name:'Remodelación de la cicatriz', time:'3 semanas – 2 años', color:'green',
        body:'El colágeno tipo III es sustituido por colágeno tipo I más grueso y organizado en haces paralelos (menor elasticidad que la piel normal). La vascularización excesiva regresa → cicatriz pálida. Los miofibroblastos sufren apoptosis. La resistencia tensil aumenta al 70–80% del normal a los 3 meses y al 80–85% máximo (nunca recupera el 100%). Una cicatriz patológica (hipertrófica o queloide) indica exceso de TGF-β1 con inhibición insuficiente de la síntesis de colágeno. El masaje, la silicona y la presión son tratamientos de primera línea para cicatrices patológicas.',
        agents:[{l:'US continuo (sobre cicatriz)',c:'amber'},{l:'Laser 830 nm',c:'pink'},{l:'Interferencial (fibrosis)',c:'green'}]},
    ],
    note:'<strong>Cicatriz hipertrófica vs queloide:</strong> la hipertrófica respeta los límites de la herida y puede regresar; el queloide invade tejido sano y raramente regresa espontáneamente. El laser 830 nm en dosis bajas (1–3 J/cm²) tiene evidencia en reducción de cicatrices hipertróficas al modular TGF-β1 y la actividad de miofibroblastos.'},
];

